/**
 * Dutch kennisbank bodies for DirectAdmin topics (TripleZero iT).
 * Topic-specific how-tos with menu paths — not genericBody filler.
 */
const BRAND = "TripleZero iT";

function p(...paras: string[]) {
  return paras.map((t) => `<p>${t}</p>`).join("\n");
}

function h2(t: string) {
  return `<h2>${t}</h2>`;
}

function ol(items: string[]) {
  return `<ol>\n${items.map((i) => `  <li>${i}</li>`).join("\n")}\n</ol>`;
}

function ul(items: string[]) {
  return `<ul>\n${items.map((i) => `  <li>${i}</li>`).join("\n")}\n</ul>`;
}

function tip(t: string) {
  return `<aside class="kb-callout kb-callout-tip"><p><strong>Tip:</strong> ${t}</p></aside>`;
}

function warn(t: string) {
  return `<aside class="kb-callout kb-callout-warn"><p><strong>Let op:</strong> ${t}</p></aside>`;
}

function outro(related?: string) {
  return p(
    `Kom je er na deze stappen niet uit? Open een ticket bij ${BRAND} via het klantenpanel. Vermeld hostname, DirectAdmin-gebruikersnaam (geen wachtwoord), domein en wat je al probeerde.`,
    related
      ? `Gerelateerd: ${related}.`
      : `Bekijk ook andere DirectAdmin-artikelen over e-mail, SSL, bestanden en backups.`,
  );
}

type Ctx = { title: string; topic: string };

export const directadminExcerptsNl: Record<string, string> = {
  "da-password-change": "Wijzig of herstel je DirectAdmin-panelwachtwoord via Account Manager of Forgot Password, en controleer daarna de login.",
  "da-password": "Pas je DirectAdmin-inlogwachtwoord aan via Account Manager → Password en test met een schone login.",
  "da-login": "Vind DirectAdmin-URL, gebruikersnaam en eerste wachtwoord via welkomstmail of TripleZero iT klantenpanel.",
  "2fa-da": "Schakel DirectAdmin Two-Step Authentication in, koppel een authenticator-app en bewaar backupcodes.",
  "cant-login": "Checklist bij mislukte DirectAdmin-login: URL, accountnaam, 2FA, IP-blokkade en lockouts.",
  "dir-password": "Beveilig een map met HTTP-auth via Password Protected Directories in DirectAdmin.",
  "what-is-da": "Wat DirectAdmin is en waar je domeinen, mail, bestanden en accountinstellingen vindt.",
  "ext-wat-is-directadmin-en-hoe-gebruik-ik-het": "Startgids: inloggen, juiste domein kiezen en veilig taken uitvoeren in DirectAdmin.",
  "reseller": "Reseller in DirectAdmin: packages, users aanmaken en limieten bewaken.",
  "da-reseller-usage": "Werken als DirectAdmin-reseller bij TripleZero iT: users, packages en escalatie naar support.",
  "directadmin-reseller-domain": "Nieuw domein/user als reseller toevoegen met package en correcte DNS.",
  "domain-missing-da": "Domein ontbreekt of laadt niet in DirectAdmin: check account, DNS, document root en suspension.",
  "add-domain-da": "Extra domein toevoegen in DirectAdmin via Domain Setup en DNS correct laten wijzen.",
  "domain-forward": "Zet een domein-forward/redirect in DirectAdmin Domain Setup of via .htaccess/Site Redirection.",
  "domain-pointer": "Domain Pointer (alias) aanmaken zodat een extra hostnaam dezelfde site toont.",
  "subdomain": "Subdomein aanmaken in DirectAdmin (bijv. shop.jouwdomein.nl) met eigen map.",
  "dkim": "Schakel DKIM in DirectAdmin in en controleer het DNS TXT-record voor betere mailaflevering.",
  "google-verify": "Voeg een Google Search Console/HTML-verificatie toe via DNS TXT of een HTML-bestand in public_html.",
  "create-mailbox": "Nieuw e-mailadres aanmaken in DirectAdmin E-mail Accounts met quota en sterk wachtwoord.",
  "email-password": "Wijzig het wachtwoord van een mailbox via E-mail Accounts → Change Password.",
  "email-forward": "Stel een e-mail forwarder in zodat berichten naar een ander adres worden doorgestuurd.",
  "email-quota": "Pas mailboxquota aan zodat een volle inbox weer ruimte krijgt.",
  "autoresponder": "Maak een automatisch antwoord (vakantie/OOO) voor een mailbox in DirectAdmin.",
  "ooo": "Out-of-office reply instellen via Autoresponders in DirectAdmin.",
  "webmail-da": "Open webmail vanuit DirectAdmin en log in met mailboxadres + mailboxwachtwoord.",
  "catchall": "Catch-all inschakelen om mail naar onbekende lokale delen op te vangen — met spamrisico.",
  "spamassassin": "Gebruik SpamAssassin in DirectAdmin om inkomende spam te filteren.",
  "spamassassin-setup": "Configureer SpamAssassin-drempels, whitelist en delete/mark-gedrag in DirectAdmin.",
  "spam-keywords": "Voeg afzenders of trefwoorden toe aan de spamfilter-lijsten in DirectAdmin.",
  "mysql": "Maak een MySQL-database en gebruiker aan via MySQL Management in DirectAdmin.",
  "ext-hoe-beheer-ik-mijn-databases-in-directadmin": "Beheer MySQL-databases: aanmaken, gebruikers, rechten en phpMyAdmin.",
  "ext-hoe-gebruik-ik-de-mysql-management-tool-in-direc": "Gebruik MySQL Management en phpMyAdmin veilig voor import/export en gebruikscontrole.",
  "filemanager": "Navigeer, upload en bewerk bestanden met de DirectAdmin File Manager.",
  "ext-hoe-gebruik-ik-de-file-manager-in-directadmin": "Praktisch File Manager-gebruik: paden, upload, extract en veilige edits.",
  "ext-hoe-wijzig-ik-bestandspermissies-chmod-in-de-fil": "Zet CHMOD veilig via File Manager: directories 755, bestanden 644 — vermijd 777.",
  "extra-ftp": "Maak een extra FTP-account met beperkte home-map voor developers of bureaus.",
  "ext-hoe-voeg-ik-een-extra-ftp-account-toe-in-directa": "Extra FTP-user aanmaken en testen met een FTP-client.",
  "tz-th-ftp-ftp-account-aanmaken-in-directadmin-20866": "FTP-account in DirectAdmin aanmaken met veilige directory-beperking en clienttest.",
  "cron": "Plan een cronjob in DirectAdmin (tijd + commando) voor onderhoudsscripts.",
  "ext-hoe-stel-ik-cronjobs-in-via-directadmin": "Cronjobs instellen en debuggen: schema, paden en output.",
  "php-version": "Wijzig de PHP-versie per domein via Domain Setup / PHP Version Select.",
  "ext-hoe-wijzig-ik-de-php-instellingen-in-directadmin": "Pas PHP-opties (memory_limit, upload_max) aan via PHP Settings / selectors.",
  "letsencrypt-da": "Installeer gratis Let’s Encrypt SSL via SSL Certificates in DirectAdmin.",
  "backup-da": "Maak en herstel een DirectAdmin-backup (Admin Backup/Create Restore of user Create/Restore).",
  "jetbackup": "Wat JetBackup is: geplande backups en restores naast native DirectAdmin-backups.",
  "ext-hoe-maak-ik-een-volledige-site-back-up-in-direct": "Volledige sitebackup via Create Backup inclusief bestanden, mail en databases.",
  "tz-w2-th-sec-jetbackup-restore-scenarios-e8bbb": "JetBackup restore-scenario’s: bestanden, mailbox of database selectief terugzetten.",
  "tz-w2-rw-bestandsbeheer-op-een-directadmin-vpsbes-70d09": "Bestandsbeheer op een DirectAdmin-VPS: File Manager, permissies en wanneer SSH nodig is.",
  "installatron": "Wat Installatron is: one-click apps (WordPress e.d.) installeren en beheren in DirectAdmin.",
  "installatron-import": "Voeg een bestaande site toe aan Installatron als die “kwijt” is uit My Applications.",
  "installatron-delete": "Verwijder een WordPress-installatie netjes via Installatron inclusief optionele DB/files.",
  "installatron-update": "Werk WordPress (core/plugins/themes) bij via Installatron updates.",
  "installatron-backup": "Maak of verwijder Installatron-backups van je WordPress-site.",
  "wp-install": "Installeer WordPress via Installatron op het juiste domein/pad met sterke admin-credentials.",
  "wp-critical": "Los een WordPress critical error op: debug, plugins uitschakelen, theme wisselen, PHP-check.",
  "wp-clone": "Kloon WordPress naar een ander domein via Installatron clone/migrate of zorgvuldige search-replace.",
  "wp-multisite": "WordPress multisite op DirectAdmin: subdomains/subdirs, DNS wildcards en Installatron-keuzes.",
  "wp-php-unsafe": "Los “onveilige PHP-versie” in WordPress op door PHP te upgraden in DirectAdmin.",
  "wp-https": "Zet WordPress-URL’s op HTTPS na SSL: siteurl/home en force redirect.",
  "htaccess": "Beveilig of stuur verkeer met .htaccess: auth, redirects en beschermde bestanden.",
  "inodes": "Wat inodes zijn: limiet op aantal bestanden/mappen — opruimen bij inode-warnings.",
  "disk-usage-da": "Schijfgebruik daalt niet na delete: trash, mail, backups recount en verborgen gebruik.",
  "bandwidth": "Wat bandbreedte/dataverkeer is en hoe je het in DirectAdmin afleest.",
  "quota-full": "Mailbox of hostingpakket vol: wat je ruimt en wat je verhoogt.",
  "usage-warning": "Betekenis van “used up X% bandwidth/disk” mails en wat je moet doen.",
  "storage-usage": "Wat schijfruimte verbruikt: sites, mail, backups, databases en logs.",
  "prevent-full": "Voorkom volle pakketten: opruimroutine, backupretentie en limietmonitoring.",
  "rename-account": "Hosting-login/accountnaam wijzigen: meestal niet self-service — wat wel kan.",
  "troubleshoot": "Eerste hulp bij mail-/site-/panelproblemen: isoleer laag (DNS, SSL, app, mail).",
  "ext-hoe-gebruik-ik-de-dns-zone-editor-in-directadmin": "Bewerk A, AAAA, CNAME, MX en TXT in de DirectAdmin DNS Zone Editor.",
  "ext-hoe-voeg-ik-een-domeinalias-domain-pointer-toe-i": "Domain pointer/alias toevoegen zodat een extra hostnaam dezelfde site serveert.",
  "ext-hoe-bekijk-ik-de-statistieken-van-mijn-website-i": "Bekijk bezoekers- en trafficstatistieken via Site Summary / AWStats / webalizer in DirectAdmin.",
  "ext-hoe-blokkeer-ik-een-ip-adres-in-directadmin": "Blokkeer misbruikende IP’s via IP Blocker / .htaccess / CSF (afhankelijk van server).",
  "ext-hoe-voeg-ik-een-extra-domein-toe-aan-mijn-hostin": "Extra domein op je hostingpakket: limiet checken, Domain Setup, DNS en SSL.",
  "ext-hoe-gebruik-ik-de-brute-force-monitor-in-directa": "Brute Force Monitor: bekijk geblokkeerde IPs en deblokkeer jezelf veilig.",
  "da-sni": "SNI op een DirectAdmin-server: meerdere certificaten per IP voor HTTPS-hosts.",
  "da-custombuild": "CustomBuild 2 updaten op een DirectAdmin-VPS: ./build update en gerichte upgrades.",
};

export const directadminTopicBuilders: Record<string, (ctx: Ctx) => string> = {
  "da-password-change": () => [
    p(`In DirectAdmin wijzig je het <strong>panelwachtwoord</strong> (user, reseller of admin) via Account Manager. Dit is niet hetzelfde als een mailbox- of FTP-wachtwoord.`,
      `Wachtwoord vergeten? Gebruik “Forgot Password” op de loginpagina indien beschikbaar, of vraag een reset via het ${BRAND} klantenpanel / ticket.`),
    h2("Voorbereiding"),
    ul([
      "DirectAdmin-URL uit je welkomstmail (vaak poort <code>2222</code>).",
      "Accountniveau: User, Reseller of Admin.",
      "Een wachtwoordmanager voor een sterk, uniek wachtwoord.",
    ]),
    h2("Wijzigen terwijl je bent ingelogd"),
    ol([
      "Log in op DirectAdmin.",
      "Open <strong>Account Manager</strong> → <strong>Password</strong> (of “Change Password” / “Wachtwoord”).",
      "Vul huidig wachtwoord in en daarna tweemaal het nieuwe.",
      "Sla op, log uit en opnieuw in ter controle.",
    ]),
    h2("Wachtwoord vergeten"),
    ol([
      "Open de DirectAdmin-loginpagina.",
      "Klik <strong>Forgot Password</strong> / “Wachtwoord vergeten” (als zichtbaar).",
      "Vul gebruikersnaam en het e-mailadres op het account in.",
      "Volg de resetlink en kies een nieuw sterk wachtwoord.",
      "Werkt dit niet? Ticket naar ${BRAND} met hostname, gebruikersnaam (geen wachtwoord) en tijdstip.",
    ]),
    h2("Controleren"),
    ul([
      "Opnieuw inloggen lukt met het nieuwe wachtwoord.",
      "Werk opgeslagen wachtwoorden in browser/FTP-clients bij.",
      "Zet bij voorkeur <strong>2FA</strong> aan na een reset.",
    ]),
    warn("Deel panelwachtwoorden nooit buiten het ticketsysteem. Bij compromise: reset ook mailbox- en FTP-wachtwoorden."),
    tip("Reseller-wachtwoorden geven toegang tot meerdere users — behandel ze strenger."),
    outro("2FA instellen; logingegevens vinden; niet kunnen inloggen."),
  ].join("\n"),

  "da-password": () => [
    p(`Als je al bent ingelogd, wijzig je het DirectAdmin-panelwachtwoord onder <strong>Account Manager → Password</strong>. Voor “vergeten wachtwoord”: zie het artikel DirectAdmin wachtwoord aanpassen.`),
    h2("Stappen"),
    ol([
      "Log in op DirectAdmin.",
      "Ga naar <strong>Account Manager</strong> → <strong>Password</strong>.",
      "Voer het oude wachtwoord in.",
      "Kies een nieuw, uniek wachtwoord en bevestig.",
      "Sla op → log uit → log opnieuw in.",
    ]),
    h2("Veelgemaakte fouten"),
    ul([
      "Mailboxwachtwoord wijzigen onder E-mail Accounts i.p.v. panelwachtwoord.",
      "Wachtwoord hergebruiken van WordPress of FTP.",
      "Als reseller het Password-scherm van de verkeerde user openen.",
    ]),
    tip("Update FileZilla en backuptools die het oude panelwachtwoord opslaan."),
    outro("2FA; logingegevens."),
  ].join("\n"),

  "da-login": () => [
    p(`Je DirectAdmin-gegevens staan in de ${BRAND}-oplevering: welkomstmail en/of productdetails in het klantenpanel. De URL wijst meestal naar poort <code>2222</code>.`),
    h2("Gegevens vinden"),
    ol([
      "Zoek in je mailbox op DirectAdmin, control panel of de serverhostname.",
      "Of: ${BRAND} klantenpanel → hosting/VPS-product → login-URL, gebruikersnaam, wachtwoord/reset.",
      "Open uitsluitend de URL die ${BRAND} communiceert.",
      "Log in met de DirectAdmin-gebruikersnaam (vaak niet je e-mailadres).",
    ]),
    warn("Phishing: typ de URL over uit het klantenpanel. Deel geen wachtwoorden via onbekende formulieren."),
    outro("Wachtwoord wijzigen; 2FA; niet inloggen."),
  ].join("\n"),

  "2fa-da": () => [
    p(`<strong>Two-Step Authentication</strong> (2FA) vraagt naast je wachtwoord een TOTP-code. Activeer dit op elk DirectAdmin-account waarmee je inlogt.`),
    h2("Stappen"),
    ol([
      "Log in op DirectAdmin.",
      "Open <strong>Account Manager</strong> → <strong>Two-Step Authentication</strong>.",
      "Kies TOTP / authenticator-app.",
      "Scan de QR-code met je app.",
      "Bevestig met de eerste code.",
      "Sla scratch/backupcodes veilig op (niet alleen in je mailbox).",
      "Test: uitloggen en opnieuw inloggen met wachtwoord + code.",
    ]),
    tip("Zonder backupcodes kun je jezelf buitensluiten bij telefoonverlies."),
    warn("Support vraagt nooit om je 2FA-codes in chat."),
    outro("Wachtwoord; niet kunnen inloggen."),
  ].join("\n"),

  "cant-login": () => [
    p(`Inlogproblemen komen meestal door verkeerde URL/poort, verkeerde username, 2FA, of een tijdelijke IP-blokkade na mislukte pogingen.`),
    h2("Checklist"),
    ol([
      "Controleer hostname + poort <code>2222</code> uit welkomstmail/klantenpanel.",
      "Probeer een privévenster.",
      "Gebruik de DirectAdmin-username, niet per se je e-mail.",
      "Reset wachtwoord via Forgot Password of ${BRAND}-ticket.",
      "Bij 2FA: actuele app-code of backupcode.",
      "Test via 4G — mogelijk Brute Force / IP-block op vast netwerk.",
      "Reseller: check of de user niet suspended is.",
    ]),
    tip("Ticket: hostname, username, letterlijke fout, tijdstip, wel/niet via 4G."),
    outro("Logingegevens; brute-force monitor; wachtwoord."),
  ].join("\n"),

  "dir-password": () => [
    p(`<strong>Password Protected Directories</strong> zet browser-login (HTTP Auth) op een map — voor staging of interne tools. Dit vervangt geen WordPress-login.`),
    h2("Stappen"),
    ol([
      "Selecteer het juiste domein in DirectAdmin.",
      "Open <strong>Advanced Features</strong> → <strong>Password Protected Directories</strong>.",
      "Kies of maak de map onder <code>public_html</code>.",
      "Stel de protected-directory prompt in.",
      "Voeg een directory-user + wachtwoord toe (los van panel-user).",
      "Test in een privévenster.",
    ]),
    warn("Gebruik HTTPS. Directory-users zijn niet hetzelfde als DirectAdmin-users."),
    outro("htaccess; File Manager; SSL."),
  ].join("\n"),

  "what-is-da": () => [
    p(`DirectAdmin is het controlpanel voor websites, e-mail, DNS, databases, FTP en backups bij ${BRAND}.`),
    h2("Voorbereiding"),
    ul(["DirectAdmin-login","Minstens één domein op het account"]),
    h2("Stappen"),
    ol(["Log in","Bekijk Account Manager (usage, password, 2FA)","Open Domain Setup voor domeinen","Open E-mail Accounts voor mailboxen","Open File Manager onder System Info & Files"]),
    h2("Controleren"),
    ul(["Domeinen en usage zichtbaar","File Manager opent zonder fout"]),
    tip(`Gebruik de zoekbalk in Evolution-skin als labels anders heten.`),
    warn(`Users wijzigen geen serverbrede CustomBuild-opties.`),
    outro(`da-login; filemanager`),
  ].join("\n"),

  "ext-wat-is-directadmin-en-hoe-gebruik-ik-het": () => [
    p(`Dagelijkse werkwijze in DirectAdmin: inloggen, domein selecteren, één wijziging tegelijk, daarna extern testen.`),
    h2("Voorbereiding"),
    ul(["Login-URL","Te beheren domein"]),
    h2("Stappen"),
    ol(["Log in","Selecteer het domein via dropdown of Domain Setup","Voer één taak uit (mail, SSL of bestanden)","Test in browser of mailclient","Log uit op gedeelde PC’s"]),
    h2("Controleren"),
    ul(["Juiste domein geselecteerd","Geen errors na opslaan"]),
    tip(`Zoekbalk rechtsboven versnelt navigatie.`),
    warn(`Wijzig niet meerdere kritieke DNS-records tegelijk.`),
    outro(`what-is-da; cant-login`),
  ].join("\n"),

  "reseller": () => [
    p(`Op reseller-niveau beheer je packages en user-accounts met schijf-, traffic- en domeinlimieten.`),
    h2("Voorbereiding"),
    ul(["Reseller-login","Package-plan"]),
    h2("Stappen"),
    ol(["Log in als reseller","Open Reseller Level → List Users / Manage Packages","Maak of pas packages aan","Create User met package, e-mail en wachtwoord","Controleer periodiek resource usage"]),
    h2("Controleren"),
    ul(["Nieuwe user logt in op :2222","Limieten matchen je aanbod"]),
    tip(`Documenteer welk package bij welk klanttype hoort.`),
    warn(`Geef klanten geen admin/root-toegang.`),
    outro(`da-reseller-usage; usage-warning`),
  ].join("\n"),

  "da-reseller-usage": () => [
    p(`${BRAND}-resellers lossen first-line issues op in DirectAdmin; serverbeheer (CustomBuild, SNI) escaleer je via ticket.`),
    h2("Voorbereiding"),
    ul(["Reseller credentials","Overzicht users"]),
    h2("Stappen"),
    ol(["Log in op reseller-level","Controleer List Users en usage","Maak users alleen binnen contractlimieten","Escaleer httpd/mailqueue/CustomBuild-problemen naar ${BRAND}"]),
    h2("Controleren"),
    ul(["Users zien eigen user-panel","Geen overselling buiten contract"]),
    tip(`Houd een runbook: zelf oplossen vs. escaleren.`),
    warn(`CustomBuild is geen eindgebruikertaak.`),
    outro(`reseller; cant-login`),
  ].join("\n"),

  "directadmin-reseller-domain": () => [
    p(`Voeg een klant toe via Create User (of extra domein) en laat DNS naar de server wijzen vóór SSL.`),
    h2("Voorbereiding"),
    ul(["Reseller-login","Package","DNS-toegang"]),
    h2("Stappen"),
    ol(["Reseller Level → Create User","Vul username, e-mail, wachtwoord, package in","Noteer nameservers of A-record van ${BRAND}","Zet DNS en wacht op propagatie","Rond SSL/mail af op user-niveau"]),
    h2("Controleren"),
    ul(["User login werkt","Domein resolved naar server-IP"]),
    tip(`Vraag Let’s Encrypt pas aan als DNS klopt.`),
    warn(`Verwar Create User niet met Domain Pointer.`),
    outro(`add-domain-da; letsencrypt-da`),
  ].join("\n"),

  "domain-missing-da": () => [
    p(`Als een domein “niet in DirectAdmin staat” of niet laadt, controleer je of het op het juiste user-account hangt en of DNS klopt.`),
    h2("Voorbereiding"),
    ul(["User/reseller-login","Verwacht domein","DNS-toegang"]),
    h2("Stappen"),
    ol(["Log in en zoek het domein onder Domain Setup","Ontbreekt het: als reseller — hangt het onder een andere user?","Controleer A/AAAA of nameservers naar ${BRAND}","Check of het account suspended is","Controleer document root in Domain Setup / File Manager"]),
    h2("Controleren"),
    ul(["Domein zichtbaar in het panel","HTTP bereikt de server"]),
    tip(`Vergelijk dig/nslookup met het server-IP uit het klantenpanel.`),
    warn(`Een Domain Pointer is geen volwaardig apart hostingaccount.`),
    outro(`add-domain-da; domain-pointer`),
  ].join("\n"),

  "add-domain-da": () => [
    p(`Voeg een extra domein toe onder Domain Setup wanneer je pakket meerdere domeinen toestaat.`),
    h2("Voorbereiding"),
    ul(["User-login","Vrije domeinslot in package","DNS-rechten"]),
    h2("Stappen"),
    ol(["Domain Setup → Add Another Domain","Vul domeinnaam in, kies PHP indien gevraagd","Bevestig aanmaken","Zet DNS (A-record of nameservers) naar de server","Wacht op propagatie vóór SSL"]),
    h2("Controleren"),
    ul(["Domein in de lijst","public_html voor het domein bestaat"]),
    tip(`Houd PHP-versie per domein bewust gelijk of verschillend.`),
    warn(`Overselling: check limiet “max domains” bij usage-fouten.`),
    outro(`subdomain; letsencrypt-da`),
  ].join("\n"),

  "domain-forward": () => [
    p(`Forward een domein of pad naar een andere URL via Site Redirection of Domain Setup — kies 301 voor permanente verhuizing.`),
    h2("Voorbereiding"),
    ul(["Domein in DirectAdmin","Doel-URL"]),
    h2("Stappen"),
    ol(["Selecteer bron-domein","Open Domain Setup → Site Redirection (of Forwarding)","Kies pad <code>/</code> of een subpad","Vul doel-URL in","Kies Permanent (301) of Temporary (302)","Test in privévenster"]),
    h2("Controleren"),
    ul(["Redirect werkt zonder loop","HTTPS-doel bereikbaar"]),
    tip(`Voor apex→www of HTTP→HTTPS is vaak SSL + force-SSL praktischer.`),
    warn(`Dubbele redirects (panel + .htaccess + WordPress) veroorzaken loops.`),
    outro(`domain-pointer; wp-https`),
  ].join("\n"),

  "domain-pointer": () => [
    p(`Een <strong>Domain Pointer</strong> laat een extra hostnaam naar dezelfde content wijzen (alias), zonder apart hostingpakket.`),
    h2("Voorbereiding"),
    ul(["User-login","Bron-domein met content","Alias-domein"]),
    h2("Stappen"),
    ol(["Domain Setup → Domain Pointers","Add Pointer: alias-hostnaam","Kies alias (zelfde site) of pointer naar map indien beschikbaar","Zet DNS van de alias naar dezelfde server","Vraag SSL aan voor de alias"]),
    h2("Controleren"),
    ul(["Alias toont dezelfde site","Certificaat dekt de alias"]),
    tip(`Voor een echt aparte site: Add Domain i.p.v. pointer.`),
    warn(`Vergeet SSL op de alias niet — anders browserfouten.`),
    outro(`add-domain-da; letsencrypt-da`),
  ].join("\n"),

  "subdomain": () => [
    p(`Maak subdomeinen onder Domain Setup → Subdomain Management; elk krijgt een map onder domains/… .`),
    h2("Voorbereiding"),
    ul(["Hoofddomein in DA","Gewenste subnaam"]),
    h2("Stappen"),
    ol(["Selecteer hoofddomein","Domain Setup → Subdomain Management → Add Subdomain","Vul naam in (zonder hoofddomein)","Noteer de document root","Zet DNS indien nodig (vaak automatisch op ${BRAND}-nameservers)","Deploy content / SSL"]),
    h2("Controleren"),
    ul(["http(s)://sub.domein bereikbaar","Juiste map in File Manager"]),
    tip(`Gebruik aparte subdomeinen voor staging i.p.v. te mixen in productie-root.`),
    warn(`Wildcard-DNS nodig bij veel dynamische subs.`),
    outro(`add-domain-da; filemanager`),
  ].join("\n"),

  "dkim": () => [
    p(`DKIM ondertekent uitgaande mail. In DirectAdmin activeer je dit per domein; het TXT-record moet in DNS staan.`),
    h2("Voorbereiding"),
    ul(["Domein geselecteerd","DNS-beheer (DA of extern)"]),
    h2("Stappen"),
    ol(["Selecteer domein","E-mail Accounts / E-mail Authentication → enable DKIM","Controleer DNS Zone of externe DNS op <code>x._domainkey</code> TXT","Verstuur testmail en check header dkim=pass"]),
    h2("Controleren"),
    ul(["DKIM enabled in panel","dkim=pass in headers"]),
    tip(`Externe DNS (Cloudflare): kopieer het record handmatig.`),
    warn(`Meerdere conflicterende DKIM-selectors breken validatie.`),
    outro(`create-mailbox; spamassassin`),
  ].join("\n"),

  "google-verify": () => [
    p(`Google-verificatie bewijst domeineigendom voor Search Console. Via DirectAdmin plaats je een TXT-record of upload je een HTML-bestand.`),
    h2("Voorbereiding"),
    ul(["DirectAdmin-login","Verificatietoken van Google"]),
    h2("Stappen"),
    ol(["Kies methode in Search Console (DNS TXT of HTML-file)","DNS: DNS Management → Add TXT op @ of google-site-verification","HTML: File Manager → public_html → upload het .html-bestand in de root","Klik Verify in Search Console"]),
    h2("Controleren"),
    ul(["Status Verified in Search Console"]),
    tip(`DNS-propagatie kan enkele minuten duren — niet meteen opnieuw een ander token aanmaken.`),
    warn(`Verwijder het HTML-bestand niet meteen na verificatie tenzij Google dat toestaat.`),
    outro(`dns zone; filemanager`),
  ].join("\n"),

  "create-mailbox": () => [
    p(`Maak mailboxen onder E-mail Accounts op het juiste domein; noteer IMAP/SMTP-gegevens voor clients.`),
    h2("Voorbereiding"),
    ul(["Domein geselecteerd","Vrije mail-quota"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Create Account","Vul local-part in (voor @)","Stel wachtwoord en quota in","Sla op","Noteer mailserverhost, poorten IMAP/SMTP uit welkomstmail of panel"]),
    h2("Controleren"),
    ul(["Webmail login werkt","Testmail verzenden/ontvangen"]),
    tip(`Gebruik unieke mailboxwachtwoorden, niet het panelwachtwoord.`),
    warn(`Catch-all vangt typos maar vergroot spam — bewust inschakelen.`),
    outro(`webmail-da; email-password`),
  ].join("\n"),

  "email-password": () => [
    p(`Mailboxwachtwoorden wijzig je per account onder E-mail Accounts — los van het DirectAdmin-panelwachtwoord.`),
    h2("Voorbereiding"),
    ul(["Welke mailbox","Nieuwe sterke wachtwoord"]),
    h2("Stappen"),
    ol(["E-mail Accounts","Selecteer de mailbox → Change Password / potlood","Stel nieuw wachtwoord in","Werk telefoon/Outlook/webmail bij","Test versturen en ontvangen"]),
    h2("Controleren"),
    ul(["Oude wachtwoord faalt","Nieuw wachtwoord werkt in webmail"]),
    tip(`Bij compromise: ook app-wachtwoorden/forwarders controleren.`),
    warn(`Verwar dit niet met Account Manager → Password.`),
    outro(`create-mailbox; cant-login`),
  ].join("\n"),

  "email-forward": () => [
    p(`Forwarders sturen inkomende mail door naar een extern of intern adres. Let op: dit is geen volledige mailbox-archivering.`),
    h2("Voorbereiding"),
    ul(["Bronadres of forwarder-naam","Doeladres"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Forwarders → Create","Vul bron en doel in","Sla op","Stuur een testmail naar de bron"]),
    h2("Controleren"),
    ul(["Testmail komt aan op doel","Geen forward-loop"]),
    tip(`Voor “kopie bewaren + doorsturen” combineer je soms mailbox + forward — check panelopties.`),
    warn(`Loops ontstaan als doel terug forwardt naar bron.`),
    outro(`create-mailbox; catchall`),
  ].join("\n"),

  "email-quota": () => [
    p(`Quota begrens je per mailbox. Bij “mailbox full” verhoog je limiet of ruim je op via webmail.`),
    h2("Voorbereiding"),
    ul(["Welke mailbox","Beschikbare accountquota"]),
    h2("Stappen"),
    ol(["E-mail Accounts","Wijzig de mailbox → Quota","Verhoog MB of zet passend limiet","Of: webmail → ruim Trash/Spam op","Controleer account-disk usage"]),
    h2("Controleren"),
    ul(["Nieuwe mail komt binnen","Usage onder limiet"]),
    tip(`Grote bijlagen en Spam-map vullen quota snel.`),
    warn(`Account-disk vol? Dan helpt alleen mailbox-quota verhogen niet.`),
    outro(`quota-full; webmail-da`),
  ].join("\n"),

  "autoresponder": () => [
    p(`Autoresponders sturen een vast antwoord op inkomende mail — ideaal voor afwezigheid.`),
    h2("Voorbereiding"),
    ul(["Mailbox","Periode en tekst"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Autoresponders → Create","Kies adres","Stel onderwerp/body in","Optioneel start/einddatum","Sla op en test vanaf extern adres"]),
    h2("Controleren"),
    ul(["Je ontvangt het autoresponse","Geen mailstorm naar mailinglijsten"]),
    tip(`Houd de tekst kort en vermeld een alternatief contact.`),
    warn(`Autorespond op catch-all of drukke alias kan spam/loops veroorzaken.`),
    outro(`ooo; create-mailbox`),
  ].join("\n"),

  "ooo": () => [
    p(`Out-of-office is een autoresponder met duidelijke afwezigheidstekst en bij voorkeur een einddatum.`),
    h2("Voorbereiding"),
    ul(["Mailbox","Einddatum"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Autoresponders","Create/Edit voor het adres","Schrijf korte OOO-tekst + alternatief contact","Zet einddatum","Test vanaf een extern account"]),
    h2("Controleren"),
    ul(["OOO komt één keer per afzender (policy afhankelijk)","Na einddatum stopt het"]),
    tip(`Zet OOO uit wanneer je terugbent — einddatum is een vangnet.`),
    warn(`Interne ticketsystemen kunnen OOO als noise zien.`),
    outro(`autoresponder`),
  ].join("\n"),

  "webmail-da": () => [
    p(`Webmail bereik je via de Roundcube/webmail-link in DirectAdmin of een webmail-URL uit de welkomstmail.`),
    h2("Voorbereiding"),
    ul(["Mailbox + wachtwoord","Webmail-URL"]),
    h2("Stappen"),
    ol(["Log in op DirectAdmin of open webmail-URL direct","Kies Roundcube (of beschikbare client)","Log in met volledig e-mailadres + mailboxwachtwoord","Controleer Inbox/Sent"]),
    h2("Controleren"),
    ul(["Mail zichtbaar","Verzenden werkt"]),
    tip(`Werkt webmail wel en Outlook niet, dan ligt het aan clientinstellingen.`),
    warn(`Panelwachtwoord ≠ mailboxwachtwoord.`),
    outro(`create-mailbox; email-password`),
  ].join("\n"),

  "catchall": () => [
    p(`Catch-all vangt adressen zoals typo@jouwdomein.nl. Handig, maar vergroot spamvolume.`),
    h2("Voorbereiding"),
    ul(["Domein","Doelmailbox"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Catch-all / Default Address","Kies doorsturen naar bestaande mailbox of fout/negeren","Sla op","Test met een niet-bestaand lokaal deel"]),
    h2("Controleren"),
    ul(["Test komt aan of wordt bewust geweigerd"]),
    tip(`Bij zware spam: catch-all uitzetten en expliciete adressen gebruiken.`),
    warn(`Catch-all + forwarders kan onverwachte loops geven.`),
    outro(`spamassassin; create-mailbox`),
  ].join("\n"),

  "spamassassin": () => [
    p(`SpamAssassin scoort berichten; je stelt drempels en optionele ban/delete-acties in per user/domein.`),
    h2("Voorbereiding"),
    ul(["User-login","Begrip van spam vs. false positives"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Spamassassin / Spam Filter","Enable SpamAssassin","Stel threshold in (begin conservatief)","Kies actie: markeer als spam / drop (voorzichtig)","Whitelist belangrijke afzenders","Test legitieme en spam-samples"]),
    h2("Controleren"),
    ul(["Minder spam in Inbox","Geen belangrijke mail kwijt"]),
    tip(`Begin met markeren i.p.v. hard delete.`),
    warn(`Te strenge score blokkeert facturen/nieuwsbrieven.`),
    outro(`spamassassin-setup; spam-keywords`),
  ].join("\n"),

  "spamassassin-setup": () => [
    p(`Fine-tune SpamAssassin nadat basis enabled is: threshold, required score, en uitzonderingen.`),
    h2("Voorbereiding"),
    ul(["SpamAssassin enabled","Lijst van vertrouwde afzenders"]),
    h2("Stappen"),
    ol(["Open Spamassassin setup","Pas required score aan in kleine stappen","Voeg whitelist/blacklist toe","Bewaar en observeer een week","Verlaag of verhoog score op basis van false positives"]),
    h2("Controleren"),
    ul(["Gewenste mail komt aan","Spam grotendeels in Spam-map"]),
    tip(`Houd een log bij van afzenders die ten onrechte geblokkeerd werden.`),
    warn(`Blocklists op DNS-bl kunnen legitieme ESP’s raken.`),
    outro(`spamassassin; spam-keywords`),
  ].join("\n"),

  "spam-keywords": () => [
    p(`Filter specifieke afzenders of woorden via blacklist/whitelist in de spamfilter-UI.`),
    h2("Voorbereiding"),
    ul(["Concrete afzender of kenmerkende spamzin"]),
    h2("Stappen"),
    ol(["E-mail Accounts → Spam Filter / Blacklist/Whitelist","Add blacklist voor hardnekkige spam","Add whitelist voor belangrijke partners","Sla op en test"]),
    h2("Controleren"),
    ul(["Blacklist blokkeert sample","Whitelist laat partnermail door"]),
    tip(`Whitelist spaarzaam gebruiken — anders omzeil je de filter.`),
    warn(`Te brede keywords (bijv. “factuur”) raken legitieme mail.`),
    outro(`spamassassin-setup`),
  ].join("\n"),

  "mysql": () => [
    p(`Databases horen bij je app (WordPress e.d.). Maak DB + user aan en noteer host, naam, user, wachtwoord.`),
    h2("Voorbereiding"),
    ul(["User-login","App die een database nodig heeft"]),
    h2("Stappen"),
    ol(["Account Manager / Databases → MySQL Management","Create Database","Create User + wachtwoord","Geef user rechten op de database","Noteer verbinding: localhost (meestal), dbnaam, user, wachtwoord"]),
    h2("Controleren"),
    ul(["Login in phpMyAdmin lukt","App connecteert"]),
    tip(`Bewaar credentials in een wachtwoordmanager.`),
    warn(`Gebruik geen root-DB-user in applicaties.`),
    outro(`filemanager; wp-install`),
  ].join("\n"),

  "ext-hoe-beheer-ik-mijn-databases-in-directadmin": () => [
    p(`Via MySQL Management beheer je databases, users en toegang tot phpMyAdmin.`),
    h2("Voorbereiding"),
    ul(["DirectAdmin-login"]),
    h2("Stappen"),
    ol(["Open MySQL Management","Bekijk bestaande databases","Maak of verwijder DB’s bewust","Beheer users/privileges","Open phpMyAdmin voor data-inspectie"]),
    h2("Controleren"),
    ul(["Lijst klopt met wat je app gebruikt"]),
    tip(`Exporteer een dump vóór destructieve wijzigingen.`),
    warn(`Verwijderen van een DB is onomkeerbaar zonder backup.`),
    outro(`mysql; backup-da`),
  ].join("\n"),

  "ext-hoe-gebruik-ik-de-mysql-management-tool-in-direc": () => [
    p(`MySQL Management is het overzicht; phpMyAdmin is voor queries/import. Werk voorzichtig op productie.`),
    h2("Voorbereiding"),
    ul(["DB-naam","Recente backup"]),
    h2("Stappen"),
    ol(["MySQL Management → selecteer DB","Open phpMyAdmin","Importeer/exporteer alleen met bekende dumps","Controleer table sizes bij schijfproblemen"]),
    h2("Controleren"),
    ul(["Export downloadbaar","Import zonder error"]),
    tip(`Test imports eerst op staging/kopie.`),
    warn(`Lange imports kunnen timeouts geven — splits dumps.`),
    outro(`mysql; disk-usage-da`),
  ].join("\n"),

  "filemanager": () => [
    p(`File Manager bewerkt bestanden op de server zonder FTP-client — handig voor snelle fixes.`),
    h2("Voorbereiding"),
    ul(["Juiste domein","Begrip van public_html"]),
    h2("Stappen"),
    ol(["System Info & Files → File Manager","Open domains/jouwdomein/public_html","Upload/extract/zip naar behoefte","Bewerk bestanden via Edit","Controleer permissies indien gevraagd"]),
    h2("Controleren"),
    ul(["Site laadt na wijziging","Geen permissiefouten"]),
    tip(`Maak een kopie van kritieke bestanden vóór edit.`),
    warn(`Verwijder nooit lomp hele public_html zonder backup.`),
    outro(`ext-hoe-gebruik-ik-de-file-manager-in-directadmin; htaccess`),
  ].join("\n"),

  "ext-hoe-gebruik-ik-de-file-manager-in-directadmin": () => [
    p(`Leer de mappenstructuur (domains/…/public_html) en veilige upload/extract-workflows.`),
    h2("Voorbereiding"),
    ul(["File Manager toegang"]),
    h2("Stappen"),
    ol(["Open File Manager","Navigeer naar het juiste domeinpad","Upload zip → Extract","Vermijd overschrijven van wp-config zonder backup","Logout op gedeelde PC"]),
    h2("Controleren"),
    ul(["Bestanden staan op verwachte plek"]),
    tip(`Gebruik FTP/SFTP voor grote transfers.`),
    warn(`Verkeerde extract-map plaatst WordPress in een submap.`),
    outro(`filemanager; installatron`),
  ].join("\n"),

  "ext-hoe-wijzig-ik-bestandspermissies-chmod-in-de-fil": () => [
    p(`Verkeerde permissies breken uploads of maken sites onveilig. Pas CHMOD gericht aan.`),
    h2("Voorbereiding"),
    ul(["Pad naar probleemmap","File Manager"]),
    h2("Stappen"),
    ol(["File Manager → selecteer bestand/map","Permissions / CHMOD","Mappen doorgaans 755, bestanden 644","wp-config vaak 440/400 volgens hardening","Test de site-functie (upload/form)"]),
    h2("Controleren"),
    ul(["Functionaliteit hersteld","Geen world-writable dirs"]),
    tip(`Zoek eerst welk pad de foutmelding noemt.`),
    warn(`777 is bijna nooit de juiste fix op gedeelde hosting.`),
    outro(`filemanager; wp-critical`),
  ].join("\n"),

  "extra-ftp": () => [
    p(`Extra FTP-accounts beperk je tot een submap zodat derden niet je hele account zien.`),
    h2("Voorbereiding"),
    ul(["User-login","Doelmap"]),
    h2("Stappen"),
    ol(["Account Manager → FTP Management → Create","Kies username en wachtwoord","Zet directory op de gewenste submap","Deel host, user, poort 21 of SFTP-gegevens volgens beleid","Test met FileZilla"]),
    h2("Controleren"),
    ul(["Login lukt","Geen toegang buiten toegewezen map"]),
    tip(`Trek accounts in na afloop van een project.`),
    warn(`Plain FTP is onversleuteld — bij voorkeur SFTP/FTPS.`),
    outro(`tz-th-ftp-ftp-account-aanmaken-in-directadmin-20866`),
  ].join("\n"),

  "ext-hoe-voeg-ik-een-extra-ftp-account-toe-in-directa": () => [
    p(`Stap-voor-stap FTP Management: account, directory, clientinstellingen.`),
    h2("Voorbereiding"),
    ul(["FTP Management toegang","Client zoals FileZilla"]),
    h2("Stappen"),
    ol(["FTP Management → Create FTP Account","Directory beperken","Noteer hostnaam (vaak serverhostname)","Verbind met expliciete FTP of SFTP indien aangeboden","Upload een testbestand"]),
    h2("Controleren"),
    ul(["Testbestand zichtbaar in File Manager"]),
    tip(`Gebruik unieke wachtwoorden per bureau.`),
    warn(`Verwar FTP-user niet met DirectAdmin-user.`),
    outro(`extra-ftp`),
  ].join("\n"),

  "tz-th-ftp-ftp-account-aanmaken-in-directadmin-20866": () => [
    p(`Concrete DirectAdmin-flow om een FTP-account te maken en te verifiëren.`),
    h2("Voorbereiding"),
    ul(["DirectAdmin user","Submap voor de FTP-user"]),
    h2("Stappen"),
    ol(["FTP Management → Create","Username/wachtwoord","Directory = gewenste jail","Sla op","FileZilla: host, user, wachtwoord, poort","Upload test.txt"]),
    h2("Controleren"),
    ul(["test.txt staat in de jail-map","Geen browse buiten jail"]),
    tip(`Verwijder ongebruikte FTP-users periodiek.`),
    warn(`Geen admin-panelwachtwoord als FTP-secret hergebruiken.`),
    outro(`extra-ftp; filemanager`),
  ].join("\n"),

  "cron": () => [
    p(`Cron runt commando’s op schema (backupscripts, WP-cron alternatief, imports).`),
    h2("Voorbereiding"),
    ul(["Juiste commando/pad","Begrip van tijdvelden"]),
    h2("Stappen"),
    ol(["Advanced Features → Cron Jobs","Create Cron Job","Stel minute/hour/day/month/weekday in","Vul commando in (volledig pad naar php/curl)","Sla op en check e-mailoutput indien ingesteld"]),
    h2("Controleren"),
    ul(["Job verschijnt in de lijst","Output/log toont succes"]),
    tip(`Test het commando eerst handmatig via SSH als je die hebt.`),
    warn(`Te frequente crons kunnen CPU/IO opjagen.`),
    outro(`ext-hoe-stel-ik-cronjobs-in-via-directadmin`),
  ].join("\n"),

  "ext-hoe-stel-ik-cronjobs-in-via-directadmin": () => [
    p(`Leer cron-syntax in DirectAdmin en hoe je mislukte jobs opspoort.`),
    h2("Voorbereiding"),
    ul(["Cron Jobs menu","Werkend shell/php-commando"]),
    h2("Stappen"),
    ol(["Open Cron Jobs","Add job met expliciet /usr/bin/php of curl-URL","Beperk mail-output of redirect naar log","Wacht op eerste run","Controleer resultaat"]),
    h2("Controleren"),
    ul(["Job runt op verwachte tijd"]),
    tip(`Gebruik DISABLE_WP_CRON + servercron voor zware WP-sites.`),
    warn(`Verkeerde paden falen stil — log altijd.`),
    outro(`cron; wp-install`),
  ].join("\n"),

  "php-version": () => [
    p(`Kies een ondersteunde PHP-versie per domein; te oud = onveilig, te nieuw = plugin-incompatibiliteit.`),
    h2("Voorbereiding"),
    ul(["Domein","Gewenste PHP-versie"]),
    h2("Stappen"),
    ol(["Selecteer domein","Domain Setup → PHP Version Select (of MultiPHP)","Kies versie","Sla op","Test site en wp-admin"]),
    h2("Controleren"),
    ul(["phpinfo of panel toont nieuwe versie","Geen fatale PHP-errors"]),
    tip(`Test plugins/thema’s na major upgrades.`),
    warn(`WordPress klaagt over “onveilige PHP” → upgrade, niet negeren.`),
    outro(`wp-php-unsafe; ext-hoe-wijzig-ik-de-php-instellingen-in-directadmin`),
  ].join("\n"),

  "ext-hoe-wijzig-ik-de-php-instellingen-in-directadmin": () => [
    p(`Naast versiekeuze kun je vaak PHP-opties tunen per domein.`),
    h2("Voorbereiding"),
    ul(["Domein","Benodigde limieten"]),
    h2("Stappen"),
    ol(["Open PHP Settings / PHP Config","Pas memory_limit, upload_max_filesize, post_max_size aan","Sla op","Herlaad de app en test uploads"]),
    h2("Controleren"),
    ul(["Nieuwe limieten zichtbaar in phpinfo","Upload werkt"]),
    tip(`Verhoog limieten stapsgewijs, niet meteen tot absurde waarden.`),
    warn(`Sommige waarden zijn serverbreed begrensd.`),
    outro(`php-version`),
  ].join("\n"),

  "letsencrypt-da": () => [
    p(`Vraag een certificaat aan als DNS al naar de server wijst; forceer daarna HTTPS.`),
    h2("Voorbereiding"),
    ul(["DNS correct","Domein geselecteerd"]),
    h2("Stappen"),
    ol(["Account Manager / SSL Certificates → Let’s Encrypt / Free & automatic","Vink domein + www indien nodig","Request/Save","Wacht op success","Optie Force SSL / redirect HTTP→HTTPS","Test https://"]),
    h2("Controleren"),
    ul(["Hangslot in browser","Geen mixed content fatale blokkades"]),
    tip(`Bij failure: check A-record en of poort 80 bereikbaar is voor validatie.`),
    warn(`Vraag geen cert aan op DNS die elders heen wijst.`),
    outro(`wp-https; domain-missing-da`),
  ].join("\n"),

  "backup-da": () => [
    p(`Back-ups kun je als user aanmaken/restoren via Create/Restore Backups; op VPS bestaat vaak ook JetBackup.`),
    h2("Voorbereiding"),
    ul(["Voldoende schijfruimte","Moment met lage traffic"]),
    h2("Stappen"),
    ol(["Create/Restore Backups","Create Backup — selecteer home, e-mail, DB’s naar wens","Wacht tot klaar","Download of laat op server staan","Restore: kies backup → Restore geselecteerde onderdelen","Test site/mail"]),
    h2("Controleren"),
    ul(["Backupbestand bestaat","Site werkt na restore-test op staging bij voorkeur"]),
    tip(`Restores kunnen data overschrijven — restore selectief.`),
    warn(`Backup op dezelfde schijf beschermt niet tegen diskfailure.`),
    outro(`jetbackup; installatron-backup`),
  ].join("\n"),

  "jetbackup": () => [
    p(`JetBackup (indien geïnstalleerd door ${BRAND}) biedt snapshots/restores van accounts, mail en DB’s via een eigen menu.`),
    h2("Voorbereiding"),
    ul(["JetBackup zichtbaar in DA","Welk restore-punt"]),
    h2("Stappen"),
    ol(["Open JetBackup in DirectAdmin","Bekijk beschikbare backups","Kies File/Mail/DB restore naar behoefte","Bevestig en wacht","Test het resultaat"]),
    h2("Controleren"),
    ul(["Restore completed zonder error","Data klopt"]),
    tip(`Noteer restore-tijdstip in tickets.`),
    warn(`Verkeerde full-account restore kan nieuwere data wissen.`),
    outro(`tz-w2-th-sec-jetbackup-restore-scenarios-e8bbb; backup-da`),
  ].join("\n"),

  "ext-hoe-maak-ik-een-volledige-site-back-up-in-direct": () => [
    p(`Selecteer alle relevante onderdelen voor een restoreerbare volledige backup.`),
    h2("Voorbereiding"),
    ul(["Vrije schijfruimte"]),
    h2("Stappen"),
    ol(["Create/Restore Backups → Create Backup","Selecteer website data, e-mail, FTP, databases","Start backup","Verifieer bestandsgrootte > 0","Download offsite indien mogelijk"]),
    h2("Controleren"),
    ul(["Backup staat in de lijst","Steekproef restore op DB of enkele files lukt"]),
    tip(`Bewaar minstens één kopie buiten de server.`),
    warn(`Volle schijf = mislukte backups — ruim eerst op.`),
    outro(`backup-da; disk-usage-da`),
  ].join("\n"),

  "tz-w2-th-sec-jetbackup-restore-scenarios-e8bbb": () => [
    p(`Kies het kleinste restore-scope dat het probleem oplost — full account alleen als nodig.`),
    h2("Voorbereiding"),
    ul(["Juiste backupdatum","Scope: files/mail/db"]),
    h2("Stappen"),
    ol(["JetBackup → backups","Kies datum","Restore files voor themes/plugins of specifieke paden","Of restore één mailbox/DB","Valideer site"]),
    h2("Controleren"),
    ul(["Probleem weg","Geen onbedoelde dataverlies"]),
    tip(`Communiceer downtime/risico aan stakeholders bij full restore.`),
    warn(`Restore overschrijft huidige staat van geselecteerde items.`),
    outro(`jetbackup; backup-da`),
  ].join("\n"),

  "tz-w2-rw-bestandsbeheer-op-een-directadmin-vpsbes-70d09": () => [
    p(`Op een DA-VPS beheer je sites via File Manager; voor systeempaden of zware taken gebruik je SSH als dat is toegestaan.`),
    h2("Voorbereiding"),
    ul(["DA-login","Eventueel SSH"]),
    h2("Stappen"),
    ol(["File Manager voor sitebestanden onder /domains","CHMOD gericht aanpassen","Grote transfers via SFTP","SSH alleen voor taken buiten user-home indien geautoriseerd","Backup vóór risicovolle deletes"]),
    h2("Controleren"),
    ul(["Site intact","Geen permission denied in apps"]),
    tip(`Houd web roots onder de user trees.`),
    warn(`Root-rm op verkeerde paden is desastreus — double-check cwd.`),
    outro(`filemanager; backup-da`),
  ].join("\n"),

  "installatron": () => [
    p(`Installatron automatiseert installatie, backups en updates van webapps vanuit DirectAdmin.`),
    h2("Voorbereiding"),
    ul(["Domein met lege of bedoelde map"]),
    h2("Stappen"),
    ol(["Open Installatron Applications Installer","Kies applicatie (WordPress)","Install → kies domein/pad, admin-user, wachtwoord","Rond af en open de site"]),
    h2("Controleren"),
    ul(["App bereikbaar op gekozen URL","App zichtbaar in My Applications"]),
    tip(`Noteer admin-URL en credentials direct in je password manager.`),
    warn(`Installeer niet over een bestaande site heen zonder backup.`),
    outro(`wp-install; installatron-backup`),
  ].join("\n"),

  "installatron-import": () => [
    p(`Import/attach brengt een handmatig geplaatste of ontkoppelde installatie terug onder Installatron-beheer.`),
    h2("Voorbereiding"),
    ul(["Pad naar bestaande app","DB-gegevens indien gevraagd"]),
    h2("Stappen"),
    ol(["Installatron → Import / Add existing","Wijs domein en pad","Vul DB-gegevens in indien nodig","Voltooi import","Controleer My Applications"]),
    h2("Controleren"),
    ul(["Site staat in de lijst","Backup/update-acties beschikbaar"]),
    tip(`Werkt import niet, re-install niet blind — check eerst files/DB.`),
    warn(`Dubbele installs in submappen veroorzaken verwarring.`),
    outro(`installatron; wp-install`),
  ].join("\n"),

  "installatron-delete": () => [
    p(`Deïnstalleer via Installatron i.p.v. alleen mappen wissen, zodat DB’s niet achterblijven.`),
    h2("Voorbereiding"),
    ul(["Juiste applicatie geselecteerd","Backup indien nodig"]),
    h2("Stappen"),
    ol(["My Applications → selecteer site","Uninstall / Delete","Kies of files/DB mee verwijderd worden","Bevestig","Controleer File Manager + MySQL Management"]),
    h2("Controleren"),
    ul(["Pad leeg of bewust bewaard","DB weg indien gekozen"]),
    tip(`Maak eerst een Installatron-backup als je ooit terug wilt.`),
    warn(`Verkeerde app uninstallen is definitief zonder backup.`),
    outro(`installatron-backup; mysql`),
  ].join("\n"),

  "installatron-update": () => [
    p(`Updates via Installatron centraliseren core/plugin/theme-upgrades met optionele pre-backup.`),
    h2("Voorbereiding"),
    ul(["Werkende backup","Onderhoudsvenster"]),
    h2("Stappen"),
    ol(["My Applications → Update","Selecteer beschikbare updates","Maak pre-update backup indien aangeboden","Voer update uit","Test front-end en wp-admin"]),
    h2("Controleren"),
    ul(["Versienummers nieuw","Geen critical error"]),
    tip(`Update plugins in batches op kritieke shops.`),
    warn(`Major PHP+WP-upgrades niet tegelijk zonder test.`),
    outro(`wp-critical; php-version`),
  ].join("\n"),

  "installatron-backup": () => [
    p(`Installatron-backups zijn handig vóór updates; ruim oude sets op tegen schijfgebruik.`),
    h2("Voorbereiding"),
    ul(["App in My Applications"]),
    h2("Stappen"),
    ol(["Selecteer applicatie → Backup","Start backup","Noteer locatie/lijst","Restore testen indien kritiek","Delete oude backups die je niet meer nodig hebt"]),
    h2("Controleren"),
    ul(["Nieuwe backup in de lijst","Schijfusage daalt na delete"]),
    tip(`Combineer met server/JetBackup voor disaster recovery.`),
    warn(`Alleen Installatron-backup is geen offsite-strategie.`),
    outro(`installatron-update; disk-usage-da`),
  ].join("\n"),

  "wp-install": () => [
    p(`Gebruik Installatron voor een schone WP-install op public_html of een submap.`),
    h2("Voorbereiding"),
    ul(["Domein","Sterke admingegevens"]),
    h2("Stappen"),
    ol(["Installatron → WordPress → Install","Kies domein en map (leeghouden voor root)","Stel site-titel, admin-user, wachtwoord, e-mail in","Disable automatische onveilige defaults waar relevant","Rond af → log in op /wp-admin"]),
    h2("Controleren"),
    ul(["Site laadt","wp-admin bereikbaar"]),
    tip(`Verwijder default admin-username “admin” bij voorkeur.`),
    warn(`Installeer niet in een map met oude files zonder opruimen.`),
    outro(`installatron; letsencrypt-da`),
  ].join("\n"),

  "wp-critical": () => [
    p(`Critical errors komen vaak door plugin/theme/PHP-incompatibiliteit na updates.`),
    h2("Voorbereiding"),
    ul(["FTP/File Manager","Recente wijziging bekend"]),
    h2("Stappen"),
    ol(["File Manager → wp-content/plugins: hernoem map van verdachte plugin","Of hernoem plugins → plugins.disabled","Zet default theme tijdelijk via wp-content/themes","Check PHP-versie","Zet WP_DEBUG tijdelijk om de fout te zien","Herstel of rollback"]),
    h2("Controleren"),
    ul(["Site terug","Oorzaak geïdentificeerd"]),
    tip(`Werkt Installatron-backup: restore van vóór de update.`),
    warn(`Laat WP_DEBUG niet permanent openbaar aan.`),
    outro(`installatron-update; php-version`),
  ].join("\n"),

  "wp-clone": () => [
    p(`Clonen vereist files+DB+URL-replace; Installatron clone is veiliger dan handmatig kopiëren.`),
    h2("Voorbereiding"),
    ul(["Bron-site in Installatron","Doel-domein"]),
    h2("Stappen"),
    ol(["My Applications → Clone / Sync (indien beschikbaar)","Kies doel-domein/pad","Laat URLs herschrijven","Test doel grondig","Pas DNS/SSL op doel toe"]),
    h2("Controleren"),
    ul(["Doel laadt zonder mixed oude URLs","Login werkt"]),
    tip(`Zoek in DB naar oude domeinnaam na clone.`),
    warn(`Twee sites één DB = gegarandeerde ellende.`),
    outro(`installatron; wp-https`),
  ].join("\n"),

  "wp-multisite": () => [
    p(`Multisite deelt één WP-core voor meerdere sites — planning van URL-modus en DNS is cruciaal.`),
    h2("Voorbereiding"),
    ul(["Lege installatie of bewuste conversie","DNS-wildcard bij subdomains"]),
    h2("Stappen"),
    ol(["Bepaal subdomains vs. subdirectories","Installeer WP (Installatron) op root","Volg WP Netwerk-setup / of Installatron multisite-optie","Zet wildcard DNS bij subdomain-modus","Configureer SSL (wildcard of per host)"]),
    h2("Controleren"),
    ul(["Tweede site bereikbaar","Supersite admin werkt"]),
    tip(`Multisite is complexer in backups/restore — documenteer.`),
    warn(`Shared hosting limieten kunnen netwerken beperken.`),
    outro(`subdomain; letsencrypt-da`),
  ].join("\n"),

  "wp-php-unsafe": () => [
    p(`WordPress detecteert EOL PHP. Upgrade via PHP Version Select en test daarna plugins.`),
    h2("Voorbereiding"),
    ul(["Domein","Beschikbare nieuwere PHP"]),
    h2("Stappen"),
    ol(["Domain Setup → PHP Version Select","Kies ondersteunde versie (8.x volgens beleid)","Sla op","Test site + wp-admin","Update plugins/themes die falen"]),
    h2("Controleren"),
    ul(["Waarschuwing weg","Geen fatale errors"]),
    tip(`Lees plugin-eisen vóór jump van 7.4 naar 8.3.`),
    warn(`Niet negeren: security-updates stoppen op EOL PHP.`),
    outro(`php-version; wp-critical`),
  ].join("\n"),

  "wp-https": () => [
    p(`Na Let’s Encrypt moet WP zelf op https:// staan om mixed content en redirect-loops te voorkomen.`),
    h2("Voorbereiding"),
    ul(["Geldig SSL-certificaat","wp-admin toegang"]),
    h2("Stappen"),
    ol(["Installeer SSL in DirectAdmin","Force SSL / redirect in panel indien beschikbaar","WP → Instellingen → Algemeen: beide URL’s op https://","Of pas toe via Installatron/WP-CLI search-replace","Purge caches","Test"]),
    h2("Controleren"),
    ul(["Hangslot ok","Geen mixed content op kernpagina’s"]),
    tip(`Check elementor/CDN caches apart.`),
    warn(`Alleen .htaccess redirect zonder URL-opties in WP geeft vaak login-loops.`),
    outro(`letsencrypt-da; installatron`),
  ].join("\n"),

  "htaccess": () => [
    p(`.htaccess beïnvloedt Apache-gedrag. Bewerk voorzichtig via File Manager en houd een kopie.`),
    h2("Voorbereiding"),
    ul(["File Manager","Backup van huidige .htaccess"]),
    h2("Stappen"),
    ol(["File Manager → public_html → .htaccess","Download/kopieer eerst","Voeg gerichte regels toe (auth, redirect, deny)","Test site onmiddellijk","Rollback bij 500"]),
    h2("Controleren"),
    ul(["Site ok","Regel doet wat bedoeld is"]),
    tip(`Directory Password in DA schrijft vaak al auth-config.`),
    warn(`Syntaxfout = HTTP 500 voor hele site.`),
    outro(`dir-password; filemanager`),
  ].join("\n"),

  "inodes": () => [
    p(`Inodes tellen bestanden, niet MB. Caches, sessions en e-mail kunnen limieten voltrekken.`),
    h2("Voorbereiding"),
    ul(["Usage-scherm in DA"]),
    h2("Stappen"),
    ol(["Account Manager → usage/inodes indien getoond","Zoek grote aantallen kleine files (cache, sessions)","Ruim softwarescaches / oude backups / mail Trash op","Vraag verhoging alleen als structureel nodig"]),
    h2("Controleren"),
    ul(["Inode-usage daalt","Warnings stoppen"]),
    tip(`Node_modules of verknalde caches zijn klassieke boosdoeners.`),
    warn(`Alleen schijf MB vrijmaken helpt niet bij inode-cap.`),
    outro(`disk-usage-da; prevent-full`),
  ].join("\n"),

  "disk-usage-da": () => [
    p(`DirectAdmin toont usage soms vertraagd; check Trash, mail, backups en Softaculous/Installatron-backups.`),
    h2("Voorbereiding"),
    ul(["Welke map je wiste"]),
    h2("Stappen"),
    ol(["Leeg Trash in File Manager/webmail","Controleer Create/Restore Backups en Installatron-backups","Check logs en cache-dirs","Wacht op recount of trigger usage refresh indien beschikbaar","Vergelijk met du via SSH op VPS"]),
    h2("Controleren"),
    ul(["Usage daalt na recount","Geen verborgen backupsets"]),
    tip(`JetBackup-snapshots tellen soms apart.`),
    warn(`Verwijderen in WP-media wist niet altijd alle thumbnails/backups.`),
    outro(`prevent-full; installatron-backup`),
  ].join("\n"),

  "bandwidth": () => [
    p(`Bandbreedte is maandelijkse traffic. Pieken komen door downloads, bots of hotlinking.`),
    h2("Voorbereiding"),
    ul(["Usage/stats toegang"]),
    h2("Stappen"),
    ol(["Bekijk bandwidth usage in Account Manager / stats","Identificeer pieken (logs/AWStats indien aanwezig)","Optimaliseer zware files/CDN","Blokkeer misbruikende IP’s indien nodig"]),
    h2("Controleren"),
    ul(["Begrip van verbruik vs. limiet"]),
    tip(`CDN verlaagt origin-traffic.`),
    warn(`Overschrijding kan throttle/suspend veroorzaken volgens package.`),
    outro(`usage-warning; ext-hoe-blokkeer-ik-een-ip-adres-in-directadmin`),
  ].join("\n"),

  "quota-full": () => [
    p(`“Vol” kan schijf, inode of mailboxquota zijn — diagnoseer welk limiet raakt.`),
    h2("Voorbereiding"),
    ul(["Foutmelding letterlijk"]),
    h2("Stappen"),
    ol(["Check account disk + inodes","Check mailbox quota","Ruim mail Trash/Spam, oude backups, caches","Verhoog mailboxquota indien accountruimte het toelaat","Ticket voor package-upgrade indien structureel"]),
    h2("Controleren"),
    ul(["Nieuwe mail/uploads werken"]),
    tip(`Grote mailboxen: archiveer lokaal i.p.v. oneindig bewaren op server.`),
    warn(`Alleen ene limiet verhogen terwijl inodes vol zijn lost niets op.`),
    outro(`email-quota; prevent-full`),
  ].join("\n"),

  "usage-warning": () => [
    p(`DirectAdmin stuurt usage-warnings vóór harde limieten. Handel vóór 100%.`),
    h2("Voorbereiding"),
    ul(["Welke resource: disk of bandwidth"]),
    h2("Stappen"),
    ol(["Open usage-grafieken in DA","Ruim disk of reduceer traffic","Plan upgrade als trend structureel is","Bevestig dat cron/backups niet exploderen"]),
    h2("Controleren"),
    ul(["Percentage daalt of stabiliseert"]),
    tip(`Negeer 80–90% warnings niet in piekmaanden.`),
    warn(`Reseller: check welke user de piek veroorzaakt.`),
    outro(`bandwidth; disk-usage-da`),
  ].join("\n"),

  "storage-usage": () => [
    p(`Schijf = som van webfiles, mailboxes, DB’s, backups en soms snapshots.`),
    h2("Voorbereiding"),
    ul(["File Manager + backuplijsten"]),
    h2("Stappen"),
    ol(["Meet public_html groottes","Check mail usage","Check MySQL sizes","Check backup/JetBackup/Installatron sets","Ruim gericht op"]),
    h2("Controleren"),
    ul(["Topverbruikers geïdentificeerd"]),
    tip(`Logs kunnen groeien zonder dat je het merkt.`),
    warn(`Dubbele full backups eten packs leeg.`),
    outro(`prevent-full; backup-da`),
  ].join("\n"),

  "prevent-full": () => [
    p(`Plan maandelijkse opschoning en retentiebeleid vóór je tegen limieten aanloopt.`),
    h2("Voorbereiding"),
    ul(["Toegang tot usage"]),
    h2("Stappen"),
    ol(["Zet vaste retentie voor Installatron/DA-backups","Leeg spam/trash maandelijks","Monitor inodes én MB","Gebruik CDN voor zware media","Upgrade proactief bij groei"]),
    h2("Controleren"),
    ul(["Warnings blijven onder drempel"]),
    tip(`Automatiseer reminders in je teamkalender.`),
    warn(`Altijd tot 99% zitten is geen strategie.`),
    outro(`usage-warning; installatron-backup`),
  ].join("\n"),

  "rename-account": () => [
    p(`De Unix/DirectAdmin-username is vaak immutable. Wachtwoord en e-mail wel; rename vraagt migratie/support.`),
    h2("Voorbereiding"),
    ul(["Huidige username"]),
    h2("Stappen"),
    ol(["Wijzig wat wél kan: Password, contact e-mail, FTP-users","Voor rename: ticket naar ${BRAND} met reden","Plan migratie (nieuwe user + content move) indien nodig"]),
    h2("Controleren"),
    ul(["Duidelijkheid over wel/niet mogelijk"]),
    tip(`Plan renames buiten kantoortijd — paths/credentials wijzigen.`),
    warn(`Zelf username forceren via SSH op managed hosting is riskant/verboden.`),
    outro(`da-password; da-login`),
  ].join("\n"),

  "troubleshoot": () => [
    p(`Structureel troubleshooten voorkomt willekeurig knoppen drukken.`),
    h2("Voorbereiding"),
    ul(["Tijdstip","Fouttekst","Wel/niet via 4G"]),
    h2("Stappen"),
    ol(["Bepaal scope: alleen jij / iedereen","Check DNS naar juiste IP","Check SSL-datum","Check panel usage/suspend","Check app (WP critical) vs. kale HTML-testbestand","Check mail via webmail vs. client","Ticket met feiten als vast"]),
    h2("Controleren"),
    ul(["Oorzaaklaag benoemd"]),
    tip(`Een <code>test.html</code> in public_html scheidt app van server.`),
    warn(`Meerdere fixes tegelijk maken root-cause onvindbaar.`),
    outro(`cant-login; wp-critical`),
  ].join("\n"),

  "ext-hoe-gebruik-ik-de-dns-zone-editor-in-directadmin": () => [
    p(`DNS Zone Editor wijzigt records op ${BRAND}-nameservers. Één wijziging tegelijk, oude waarde noteren.`),
    h2("Voorbereiding"),
    ul(["Domein op DA-DNS","Welk record"]),
    h2("Stappen"),
    ol(["DNS Management → zone van het domein","Edit/Add record","TTL bewust zetten","Sla op","Verifieer met dig/nslookup"]),
    h2("Controleren"),
    ul(["Nieuw record zichtbaar extern na TTL"]),
    tip(`Externe DNS (Cloudflare): wijzig daar, niet in DA.`),
    warn(`CNAME op apex (@) is meestal ongeldig.`),
    outro(`domain-forward; google-verify`),
  ].join("\n"),

  "ext-hoe-voeg-ik-een-domeinalias-domain-pointer-toe-i": () => [
    p(`Alias/pointer koppelt een hostnaam aan bestaande content; DNS moet meekomen.`),
    h2("Voorbereiding"),
    ul(["Alias-host","Bron-domein"]),
    h2("Stappen"),
    ol(["Domain Pointers → Add","Kies alias","Zet DNS","SSL voor alias","Test"]),
    h2("Controleren"),
    ul(["Alias toont site","SSL ok"]),
    tip(`Voor aparte content: Add Domain.`),
    warn(`Vergeten SSL op alias = browserwarning.`),
    outro(`domain-pointer; letsencrypt-da`),
  ].join("\n"),

  "ext-hoe-bekijk-ik-de-statistieken-van-mijn-website-i": () => [
    p(`Stats-tools tonen hits, bandwidth en paden — nuttig bij pieken of misbruik.`),
    h2("Voorbereiding"),
    ul(["Stats ingeschakeld op account"]),
    h2("Stappen"),
    ol(["Open Site Summary / AWStats / Logs","Bekijk periode en top pages","Correleer met bandwidth usage","Neem actie bij botpieken"]),
    h2("Controleren"),
    ul(["Stats laden","Pieken verklaard"]),
    tip(`Privacy: stats bevatten IP’s — behandel als gevoelig.`),
    warn(`Caching/CDN kan origin-stats lager tonen.`),
    outro(`bandwidth; ext-hoe-blokkeer-ik-een-ip-adres-in-directadmin`),
  ].join("\n"),

  "ext-hoe-blokkeer-ik-een-ip-adres-in-directadmin": () => [
    p(`IP Blocker of htaccess deny stopt hinderlijk verkeer naar jouw user-sites.`),
    h2("Voorbereiding"),
    ul(["Exact IP","Bewijs uit logs/stats"]),
    h2("Stappen"),
    ol(["Advanced Features → IP Blocker (indien aanwezig)","Of File Manager → .htaccess deny from IP","Test dat jij niet zelf geblokkeerd bent","Monitor of aanval stopt"]),
    h2("Controleren"),
    ul(["IP krijgt 403","Legitieme users ok"]),
    tip(`Blokkeer geen hele ranges zonder noodzaak.`),
    warn(`Bij serverbrede aanvallen: ticket ${BRAND} i.p.v. alleen user-blocker.`),
    outro(`troubleshoot; htaccess`),
  ].join("\n"),

  "ext-hoe-voeg-ik-een-extra-domein-toe-aan-mijn-hostin": () => [
    p(`Controleer max domains, voeg toe via Domain Setup, wijs DNS, daarna SSL/mail.`),
    h2("Voorbereiding"),
    ul(["Vrije domeinslot","DNS-toegang"]),
    h2("Stappen"),
    ol(["Check package limits","Domain Setup → Add Another Domain","DNS A/NS zetten","Wacht propagatie","SSL + eventueel mailboxen"]),
    h2("Controleren"),
    ul(["Domein actief","HTTPS werkt"]),
    tip(`Subdomeinen tellen soms apart van addon-domeinen.`),
    warn(`Zonder DNS blijft Add Domain “leeg” voelen.`),
    outro(`add-domain-da; letsencrypt-da`),
  ].join("\n"),

  "ext-hoe-gebruik-ik-de-brute-force-monitor-in-directa": () => [
    p(`BFM beschermt DirectAdmin/services tegen password guessing; false positives blokkeren jouw IP.`),
    h2("Voorbereiding"),
    ul(["BFM-toegang of reseller/admin","Eigen IP"]),
    h2("Stappen"),
    ol(["Admin/Reseller → Brute Force Monitor (of user notice)","Zoek je IP in blocked list","Unblock indien legitiem","Reset wachtwoord als er echte aanvallen waren","Overweeg 2FA"]),
    h2("Controleren"),
    ul(["Login werkt weer vanaf jouw IP"]),
    tip(`Kom je er niet in: ticket met je IP vanaf 4G.`),
    warn(`Herhaaldelijk falen door verkeerd wachtwoord triggert blocks.`),
    outro(`cant-login; 2fa-da`),
  ].join("\n"),

  "da-sni": () => [
    p(`SNI laat de webserver het juiste certificaat kiezen per hostnaam. Op VPS activeer/controleer je dit op serverniveau.`),
    h2("Voorbereiding"),
    ul(["Root/SSH of ${BRAND}-managed VPS","CustomBuild"]),
    h2("Stappen"),
    ol(["Bevestig of SNI al standaard aan staat op moderne stacks","Bij eigen beheer: controleer Apache/Nginx/OpenLiteSpeed SNI-config via CustomBuild docs","Vraag certificaten per host in DirectAdmin SSL","Test meerdere HTTPS-vhosts op hetzelfde IP"]),
    h2("Controleren"),
    ul(["Elke host toont eigen cert SAN/CN"]),
    tip(`Op shared hosting regelt ${BRAND} SNI — user hoeft niets te “enablen”.`),
    warn(`Zonder SNI op oude IP-based SSL faalt multi-cert.`),
    outro(`letsencrypt-da; da-custombuild`),
  ].join("\n"),

  "da-custombuild": () => [
    p(`CustomBuild beheert webstack-componenten. Alleen uitvoeren met root op VPS/dedicated — niet op shared user.`),
    h2("Voorbereiding"),
    ul(["SSH root","Onderhoudsvenster","Recente backup/snapshot"]),
    h2("Stappen"),
    ol(["SSH naar de server","cd /usr/local/directadmin/custombuild","./build update","./build versions om updates te zien","Voer gerichte ./build php_n / nginx/apache etc. uit volgens release notes","Test sites en panel"]),
    h2("Controleren"),
    ul(["Services draaien","Sites ok"]),
    tip(`Lees changelogs vóór major PHP upgrades.`),
    warn(`Blind ./build all op productie zonder snapshot is riskant.`),
    outro(`da-sni; php-version`),
  ].join("\n"),

};
