import { loadFaqPack } from "@/content/faq-i18n/load";

export type FaqItem = {
  id: string;
  question: string;
  answer: string;
};

export type FaqCategory = {
  id: string;
  title: string;
  items: FaqItem[];
};

export type FaqContent = {
  title: string;
  subtitle: string;
  categories: FaqCategory[];
  ctaTitle: string;
  ctaText: string;
  ctaButton: string;
};

function q(id: string, question: string, answer: string): FaqItem {
  return { id, question, answer };
}

const nl: FaqContent = {
  title: "Veelgestelde vragen",
  subtitle:
    "Uitgebreide vragen en antwoorden — van AI, AEO, GEO en SEO tot design, domeinnamen, hosting, marketing, social media, support en meer.",
  ctaTitle: "Nog hulp nodig?",
  ctaText:
    "Staat jullie vraag er niet tussen? Neem contact op — we reageren zo snel mogelijk.",
  ctaButton: "Neem contact op",
  categories: [
    {
      id: "algemeen",
      title: "Algemeen",
      items: [
        q("alg-1", "Wat doet TripleZero iT precies?", "TripleZero iT combineert webdesign, WordPress-support, digital marketing, zoekzichtbaarheid (AEO, GEO/lokaal en SEO), design en hosting. We helpen merken sneller gevonden te worden, betere websites te bouwen en meetbaar te groeien."),
        q("alg-2", "Hoe begin ik met TripleZero iT?", "Neem contact op of plan een afspraak. We doen een korte intake, kijken naar doelen en stack, en stellen daarna een concreet voorstel op met planning en KPI’s."),
        q("alg-3", "Voor welke bedrijven werken jullie?", "We werken voor MKB, scale-ups, e-commerce, agencies en internationale merken. Dat kan naast een bestaand team, of als full-service partner."),
        q("alg-4", "Werken jullie alleen in Nederland?", "Nee. We bedienen klanten in de Benelux en internationaal, met Nederlandstalige én Engelstalige trajecten."),
        q("alg-5", "Hoe verloopt een typisch traject?", "Een traject loopt meestal zo: intake → audit of scan → plan → uitvoering in sprints → meting → optimalisatie. Jullie krijgen duidelijke milestones en rapportage, zodat altijd helder is waar we staan."),
        q("alg-6", "Kan ik meerdere diensten combineren?", "Ja. Veel klanten combineren bijvoorbeeld webdesign + SEO + ads, of WordPress-onderhoud + hosting + security. We stemmen de mix af op jullie doelen en budget."),
        q("alg-7", "Hoe snel kunnen jullie starten?", "Dat hangt af van onze capaciteit, maar na akkoord starten we vaak binnen enkele werkdagen. Spoedtrajecten — zoals bugs, malware of downtime — pakken we met voorrang op, zodat we daar zo snel mogelijk mee aan de slag kunnen."),
        q("alg-8", "Werken jullie remote of on-site?", "We werken primair remote, met duidelijke communicatie via mail, chat en calls. On-site is op verzoek bespreekbaar als het project dat nodig maakt."),
        q("alg-9", "Hoe communiceert het team de voortgang?", "We houden jullie op de hoogte via vaste updates, tickets of een dashboard waar dat relevant is, plus sprint- of maandrapporten met acties en resultaten."),
        q("alg-10", "Wat hebben jullie nodig om te starten?", "Om te starten hebben we toegang tot website en hosting (als dat nodig is), jullie doelen, merkrichtlijnen, analytics-accounts en eventuele bestaande tools. Ontbreekt er iets, dan helpen we dat eerst op orde te krijgen."),
        q("alg-11", "Zijn jullie diensten geschikt voor startups?", "Ja. We schalen van lean landingspagina’s en AI-scans tot volledige groei-setups, zodat de aanpak meegroeit wanneer jullie groeien."),
        q("alg-12", "Hoe zit het met eigendom van werk en accounts?", "Jullie domein, content, code-repositories en ad-accounts blijven van jullie. Bij oplevering leveren we de bestanden en documentatie over, zodat alles netjes in eigen beheer blijft."),
        q("alg-13", "Kunnen jullie bestaande leveranciers overnemen of samenwerken?", "Ja. We werken soepel naast developers, marketeers of agencies, of we nemen onderhoud en optimalisatie over zonder het bestaande werk onnodig overhoop te halen."),
      ],
    },
    {
      id: "ai",
      title: "AI",
      items: [
        q("ai-1", "Wat is een AI-scan bij TripleZero iT?", "Een AI-readiness scan beoordeelt hoe goed jullie site vindbaar is voor klassieke zoekmachines, AI-antwoorden én lokale of geografische zoekresultaten (AEO, GEO, SEO en de technische basis)."),
        q("ai-2", "Wat meet de AI-scan precies?", "De scan meet onder meer AEO-signalen, GEO/lokale vindbaarheid, SEO-fundamentals, contentstructuur, performance-indicaties en AI-readiness. Jullie krijgen scores én concrete verbeterpunten."),
        q("ai-3", "Hoe vaak moet ik een AI-scan doen?", "Minimaal bij grote sitewijzigingen of campagnes. Voor actieve merken adviseren we periodieke scans, bijvoorbeeld elk kwartaal, zodat jullie zichtbaar blijven in zoek- én AI-resultaten."),
        q("ai-4", "Helpt AI alleen bij content?", "Nee. AI raakt ook technische vindbaarheid, structured data, interne linking, FAQ-blokken en de manier waarop merkinformatie wordt samengevat in AI-antwoorden."),
        q("ai-5", "Kunnen jullie AI in onze workflow integreren?", "Ja. We kunnen AI inzetten voor content-assistentie, automatisering, chatbot- of ticketflows, data-koppelingen en maatwerk-API’s rond AI-tools."),
        q("ai-6", "Vervangt AI jullie strategisch werk?", "Nee. AI versnelt analyse en productie, maar strategie, merktoon en conversiebeslissingen blijven menselijk en meetbaar."),
        q("ai-7", "Is AI-content veilig voor SEO?", "Alleen met menselijke review, unieke inzichten en E-E-A-T. We vermijden dunne, generieke teksten die rankings schaden."),
        q("ai-8", "Wat is AI-readiness voor mijn merk?", "Dat is de mate waarin jullie site, content en data zo zijn ingericht dat AI-systemen jullie correct kunnen citeren, aanbevelen en uitleggen."),
        q("ai-9", "Kunnen jullie AI-agents in het dashboard inzetten?", "Ja. In het klantportaal zien jullie AI-agents voor onder meer SEO, content, social en ads — inclusief status en taken."),
        q("ai-10", "Werken jullie met ChatGPT, Claude of andere tools?", "We kiezen tools per use-case. Belangrijk is governance: bronnen, factcheck, merkrichtlijnen en privacy, zodat AI-inzet betrouwbaar blijft."),
        q("ai-11", "Helpt AI bij supporttickets?", "Ja, voor triaging en snellere antwoorden. Complexe of gevoelige cases escaleren we altijd naar een menselijke medewerker."),
        q("ai-12", "Wat kost een AI-traject?", "Dat loopt van een gratis of instap AI-scan tot maandelijkse AI- en marketing-retainers. Na de intake krijgen jullie een helder voorstel."),
        q("ai-13", "Hoe meet ik ROI van AI-initiatieven?", "Via KPI’s zoals traffic, leads, time-saved, content-output, ticket-resolutie en conversie. Die meten we vooraf in het plan, zodat resultaat zichtbaar blijft."),
      ],
    },
    {
      id: "aeo-geo-seo",
      title: "AEO, GEO en SEO",
      items: [
        q("seo-1", "Wat is het verschil tussen AEO, GEO en SEO?", "AEO (Answer Engine Optimization) richt zich op AI-antwoorden. GEO (Geographic Search Engine Optimization) versterkt lokale en regionale vindbaarheid in Maps, local packs en locatiegericht zoeken. SEO optimaliseert voor klassieke zoekmachines."),
        q("seo-2", "Waarom is AEO/GEO nu belangrijk?", "Steeds meer zoekers krijgen antwoorden via AI én zoeken lokaal (“bij mij in de buurt”). Zonder AEO missen jullie AI-citaties; zonder GEO missen jullie lokale leads — ook als klassieke SEO goed is."),
        q("seo-3", "Hoe starten jullie een SEO-traject?", "We starten met een technische audit, keyword- en intent-onderzoek, een contentgap-analyse en een prioriteitenroadmap die gekoppeld is aan jullie business-KPI’s."),
        q("seo-4", "Hoe lang duurt het voor SEO-resultaten zichtbaar zijn?", "Technische wins kunnen snel zichtbaar zijn. Organische groei bouwt meestal over weken tot maanden, afhankelijk van concurrentie en hoe consequent we uitvoeren."),
        q("seo-5", "Doen jullie ook lokale SEO?", "Ja. We werken aan Google Business Profile, lokale landingspagina’s, NAP-consistentie, reviews en lokale contentclusters, zodat jullie beter gevonden worden in de regio."),
        q("seo-6", "Wat is technical SEO bij jullie?", "Technical SEO dekt crawlability, indexatie, Core Web Vitals, structured data, sitemap en robots, canonicals, interne linking en foutopsporing — alles wat zoekmachines nodig hebben om de site goed te begrijpen."),
        q("seo-7", "Helpen jullie met content voor SEO?", "Ja. We maken briefings, outlines, blogs, landingspagina’s en FAQ’s die zoekintentie matchen én AI-vriendelijk gestructureerd zijn."),
        q("seo-8", "Wat is E-E-A-T en waarom telt het?", "E-E-A-T staat voor Experience, Expertise, Authoritativeness en Trust. Sterke E-E-A-T helpt rankings én de geloofwaardigheid van jullie merk in AI-samenvattingen."),
        q("seo-9", "Doen jullie linkbuilding?", "Ja, ethisch en relevant: digitale PR, partnerships en content assets. Spammy linkschema’s doen we niet."),
        q("seo-10", "Kunnen jullie bestaande SEO-schade herstellen?", "Ja. We herstellen schade na updates, toxic links, indexatieproblemen of content-cannibalization, en zetten daarna een schone groeilijn uit."),
        q("seo-11", "Hoe rapporteren jullie SEO-voortgang?", "Maandelijks of per sprint rapporteren we rankings, traffic, conversies, technische issues en next actions, zodat duidelijk is wat we gedaan hebben en wat volgt."),
        q("seo-12", "Werkt SEO voor e-commerce?", "Zeker. We optimaliseren product- en category-SEO, faceted navigation, reviews, structured data en content hubs rond koopintentie."),
        q("seo-13", "Is SEO een eenmalig project of doorlopend?", "De beste resultaten komen uit doorlopende optimalisatie. Eenmalige audits helpen, maar concurrentie staat niet stil — daarom blijven we meten en bijsturen."),
        q("seo-14", "Helpen jullie met internationale SEO?", "Ja. We regelen hreflang, marktonderzoek per land of taal, contentlokalisatie en technische multi-locale setups."),
      ],
    },
    {
      id: "adverteren",
      title: "Adverteren",
      items: [
        q("ads-1", "Welke advertentiekanalen ondersteunen jullie?", "We ondersteunen Google Ads, Meta (Facebook/Instagram), LinkedIn, en waar relevant YouTube of retargeting — afgestemd op funnel en budget."),
        q("ads-2", "Hoe bepalen jullie het juiste advertentiebudget?", "We bepalen het budget op basis van doelen (leads of sales), CAC-doel, marktprijzen en een testfase. We starten lean en schalen wat werkt."),
        q("ads-3", "Wat is jullie aanpak voor Google Ads?", "We zetten een heldere accountstructuur neer, mappen zoekintentie, voegen negatieve keywords toe, checken landingpage-fit, richten conversietracking in en optimaliseren wekelijks."),
        q("ads-4", "Kunnen jullie Meta Ads voor e-commerce draaien?", "Ja. We draaien catalogus- en retargetingcampagnes, testen creatives en audiences, en sturen bij om ROAS te verbeteren."),
        q("ads-5", "Hoe meten jullie advertentie-succes?", "We meten conversies, CPA/CAC, ROAS, leadkwaliteit en pipeline — niet alleen klikken. Zo sturen we op resultaat in plaats van op volume."),
        q("ads-6", "Wat als tracking niet klopt?", "Dan fixen we tagging (GTM, GA4 en pixels), consent mode waar nodig, en server-side opties voor betrouwbaardere data."),
        q("ads-7", "Doen jullie ook B2B LinkedIn Ads?", "Ja. We werken met scherpe targeting, leadgen-forms of landingspagina’s en content die decision-makers aanspreekt."),
        q("ads-8", "Hoe snel zie ik resultaat uit ads?", "Verkeer kan direct binnenkomen. Stabiele CPA of ROAS vraagt meestal 2 tot 6 weken leertijd en creatieve iteratie."),
        q("ads-9", "Maken jullie ook ads-creatives?", "Ja. We maken copy, visuals en testvarianten. Design en media-creatie kunnen we meenemen, zodat campagnes niet op creatives hoeven te wachten."),
        q("ads-10", "Kunnen ads en SEO elkaar versterken?", "Absoluut. Zoekdata uit ads voedt SEO; sterke organische pagina’s verlagen CPA en verhogen de Quality Score."),
        q("ads-11", "Beheren jullie bestaande ad-accounts?", "Ja. We auditen, herstructureren en optimaliseren zonder onnodig opnieuw te beginnen."),
        q("ads-12", "Hoe voorkomen jullie verspild ad-budget?", "We voorkomen verspilling met negatieve keywords, audience exclusions, budget caps, geofencing, frequency control en het snel stopzetten van underperformers."),
        q("ads-13", "Is remarketing nog relevant?", "Ja, mits privacy-compliant en met sterke creatives en offers. Het blijft vaak de efficiëntste laag in de funnel."),
      ],
    },
    {
      id: "design",
      title: "Design",
      items: [
        q("des-1", "Welke design-diensten bieden jullie?", "We bieden logo’s, merkidentiteit, visitekaartjes, briefpapier, flyers, posters, stickers, magazines of brochures en digitale visuals."),
        q("des-2", "In welke tools werken jullie?", "We werken in Adobe Photoshop, Illustrator en InDesign, zodat bestanden drukkerij-klaar en professioneel uitwisselbaar zijn."),
        q("des-3", "Leveren jullie drukklare bestanden?", "Ja. We leveren CMYK, bleed, snijmerken en de juiste PDF/X-export waar nodig, plus screen-varianten voor digitaal gebruik."),
        q("des-4", "Hoe verloopt een logotraject?", "Een logotraject loopt van briefing naar concepten, daarna feedbackrondes, en eindigt met finale vectorbestanden (SVG/PDF/AI) en basisrichtlijnen."),
        q("des-5", "Kunnen jullie ons bestaande merk updaten?", "Ja. We refreshen logo, kleur, typografie en toepassingen zonder de herkenning te breken."),
        q("des-6", "Maken jullie ook social templates?", "Ja. We maken consistente templates voor posts, stories en ads, zodat jullie team snel en herkenbaar kan publiceren."),
        q("des-7", "Wat is het verschil tussen digitaal en print design?", "Print vraagt kleurruimte, resolutie en snijmarges; digitaal vraagt scherpte op schermen en snelle laadtijden. Wij leveren beide correct, afgestemd op het kanaal."),
        q("des-8", "Kunnen jullie magazines of brochures opmaken?", "Ja. We maken meerpagina-layouts in InDesign met grid, stijlen en prepress-checks, klaar voor druk of digitale verspreiding."),
        q("des-9", "Helpen jullie met drukwerk?", "Ja. We ontwerpen én kunnen drukken in kleine of grote oplages — van visitekaartjes en stickers tot flyers, posters en brochures — met proofs en afstemming tot aan levering."),
        q("des-10", "Hoeveel feedbackrondes zitten erin?", "Meestal zitten er 2 tot 3 gestructureerde rondes in. Extra rondes zijn mogelijk in overleg."),
        q("des-11", "Krijgen we bronbestanden?", "Ja, binnen de afgesproken oplevering. Dat kan AI, PSD of INDD zijn, of een export pack — afhankelijk van wat we hebben afgesproken."),
        q("des-12", "Kunnen design en webdesign samen lopen?", "Ja. Merkdesign en UI-systemen stemmen we af, zodat print en website één geheel vormen."),
        q("des-13", "Waar vind ik meer over Digital Design?", "Meer informatie staat op /digital-design en via de diensten Digital Design in het menu."),
      ],
    },
    {
      id: "marketing",
      title: "Marketing",
      items: [
        q("mkt-1", "Welke marketingdiensten bieden jullie?", "We bieden AEO/GEO/SEO, content, social, ads, e-commerce groei, product listing, community management en data entry."),
        q("mkt-2", "Hoe maken jullie een marketingstrategie?", "We bouwen een strategie rond doelen, audience, positionering, kanalenmix, contentpijplijn en KPI’s — pragmatisch en uitvoerbaar, niet alleen op papier."),
        q("mkt-3", "Wat is full-funnel marketing bij jullie?", "Full-funnel loopt van awareness (content en ads) via overweging (cases en SEO) tot conversie (landingspagina’s en CRM) en daarna retentie, zodat elk stadium een duidelijke rol heeft."),
        q("mkt-4", "Helpen jullie met positionering?", "Ja. Heldere positionering voorkomt versnipperde campagnes en zwakke conversie."),
        q("mkt-5", "Kunnen jullie content writing leveren?", "Ja. We schrijven blogs, website copy, newsletters, landingspagina’s en sales copy — SEO- én conversiegericht."),
        q("mkt-6", "Doen jullie e-commerce marketing?", "Ja. We werken aan productfeeds, listing quality, CRO, ads en SEO voor categorieën en producten."),
        q("mkt-7", "Wat is CRO?", "CRO is Conversion Rate Optimization: het verbeteren van pagina’s, funnels en UX zodat meer bezoekers converteren."),
        q("mkt-8", "Hoe rapporteren jullie marketingresultaten?", "We rapporteren via dashboards of rapporten met traffic, leads, sales, CPA/ROAS en learnings per kanaal, inclusief wat we daarna doen."),
        q("mkt-9", "Werken jullie met ons interne marketingteam?", "Ja. We kunnen uitvoeren, sparren of een specialistisch deel overnemen, bijvoorbeeld alleen SEO of alleen ads."),
        q("mkt-10", "Hoe snel starten jullie campagnes?", "Na tracking en setup gaan campagnes vaak binnen 1 tot 2 weken live. Contenttrajecten lopen daar parallel aan, zodat creatives en pagina’s op tijd klaarstaan."),
        q("mkt-11", "Helpen jullie met e-mailmarketing?", "Ja. We maken flows, nieuwsbrieven en copy. Integratie met CRM of e-commerce is mogelijk."),
        q("mkt-12", "Is marketing een maandcontract?", "Retainers zijn gebruikelijk voor doorlopende groei. Projecten zoals een audit, redesign of launch kunnen eenmalig."),
        q("mkt-13", "Hoe voorkomen jullie “busy marketing” zonder resultaat?", "Elke activiteit hangt aan KPI’s. Underperforming tactieken stoppen we of verbeteren we met data, zodat budget naar wat werkt gaat."),
      ],
    },
    {
      id: "social-media",
      title: "Social Media",
      items: [
        q("soc-1", "Welke social kanalen beheren jullie?", "We beheren vooral LinkedIn, Instagram en Facebook, en waar relevant X of TikTok — op basis van audience, niet van hype."),
        q("soc-2", "Wat zit er in social media management?", "Social media management omvat strategie, contentkalender, creatie en scheduling, community replies, rapportage en doorlopende optimalisatie."),
        q("soc-3", "Maken jullie ook de visuals en video’s?", "Ja, via media creation: stilstaand beeld, carrousels, short-form video en templates."),
        q("soc-4", "Hoe vaak posten jullie?", "Dat hangt af van kanaal en doelen. Typisch posten we 3 tot 5 keer per week per kernkanaal, met kwaliteit boven volume."),
        q("soc-5", "Helpen jullie met community management?", "Ja. We doen moderatie, reacties, DM’s en reputatiezorg volgens de afgesproken tone-of-voice."),
        q("soc-6", "Kunnen social en ads gecombineerd worden?", "Ja. Organische content voedt ads-creatives; ads schalen wat organisch aanslaat."),
        q("soc-7", "Hoe meten jullie social succes?", "We meten bereik, engagement, click-outs, leads en assisted conversions — niet alleen likes. Zo zien we wat écht bijdraagt aan groei."),
        q("soc-8", "Werken jullie met influencers?", "Op verzoek wel: selectie, briefing en tracking. We focussen op fit en meetbare outcomes, niet op bereik alleen."),
        q("soc-9", "Kunnen jullie crisiscommunicatie ondersteunen?", "Ja. We werken met snelle response-protocollen en stemmen af met jullie team, zodat reacties consistent en onder controle blijven."),
        q("soc-10", "Helpen jullie LinkedIn voor B2B thought leadership?", "Ja. We maken persoonlijke én company content, carrousels, cases en employee advocacy, zodat expertise zichtbaar wordt."),
        q("soc-11", "Leveren jullie een contentkalender?", "Ja. We leveren een maand- of kwartaalplanning met thema’s, formats en deadlines."),
        q("soc-12", "Wat als we al een social manager hebben?", "Dan kunnen we specialiseren in creatives, ads of strategie, of piekperiodes ondersteunen zonder het bestaande team te vervangen."),
        q("soc-13", "Hoe snel zien we groei op social?", "Consistentie telt. Significante groei vraagt meestal weken tot maanden; met ads-support gaat het vaak sneller."),
      ],
    },
    {
      id: "support",
      title: "Support",
      items: [
        q("sup-1", "Welke support bieden jullie?", "We bieden WordPress-support, maatwerk website-support, tickets en live chat, onderhoud, security, performance en incident response."),
        q("sup-2", "Hoe bereik ik support?", "Via contact, een afspraak, tickets in het dashboard of live chat op de site. Spoedcases markeren we als prioriteit."),
        q("sup-3", "Wat is jullie responstijd?", "We mikken op een snelle eerste response, vaak binnen één werkdag. Bij kritieke downtime reageren we sneller. De exacte SLA’s staan in de supportpakketten."),
        q("sup-4", "Bieden jullie 24/7 monitoring?", "Ja, in relevante support- en hostingpakketten: monitoring, backups en alerts, zodat problemen eerder zichtbaar zijn."),
        q("sup-5", "Kunnen jullie malware verwijderen?", "Ja — zowel op WordPress als op maatwerk stacks — inclusief harden en nazorg, zodat de site schoon én beter beschermd terugkomt."),
        q("sup-6", "Doen jullie WordPress-updates voor ons?", "Ja, via “Onderhoud en updates”: core, plugins en themes, met backup en checks voordat en nadat we updaten."),
        q("sup-7", "Helpen jullie bij hostingproblemen?", "Ja. We diagnosticeren, migrieren of optimaliseren hosting, VPS en domeinen tot de site weer stabiel draait."),
        q("sup-8", "Wat als mijn site platligt?", "Meld het als spoed. We herstellen waar mogelijk via backups, server checks en een hotfix, en houden jullie tussentijds op de hoogte van de status."),
        q("sup-9", "Is er een klantportaal?", "Ja. Ingelogde klanten zien dashboard, tickets, projecten en waar relevant CRM of facturen."),
        q("sup-10", "Kunnen meerdere teamleden tickets openen?", "Ja, afhankelijk van de accountrollen (client, manager of admin)."),
        q("sup-11", "Wat zit er in Basic/Standard/Premium support?", "Hogere pakketten dekken meer sites, snellere opvolging en bredere dekking (updates, malware, speed, SEO). De details staan op de supportpagina’s."),
        q("sup-12", "Helpen jullie ook bij niet-technische vragen?", "Ja, over diensten, facturatie en account. Hoe diep we technisch meegaan hangt af van jullie pakket."),
        q("sup-13", "Kan ik support later upgraden?", "Ja. Jullie kunnen opschalen wanneer verkeer, risico of teambehoefte groeit."),
      ],
    },
    {
      id: "webdesign",
      title: "Webdesign",
      items: [
        q("web-1", "Bouwen jullie alleen WordPress-sites?", "Nee. Naast WordPress doen we maatwerk webdesign in HTML/CSS/JS, PHP en Next.js — los van de WordPress-diensten."),
        q("web-2", "Wat houdt Website Support in?", "Website Support dekt ontwerp, development, onderhoud, security, performance, backups of migratie en API-integraties voor custom stacks."),
        q("web-3", "Kunnen jullie een bestaande site redesignen?", "Ja. We doen een UX/UI-refresh, conversieverbetering en technische modernisering, zonder alles weg te gooien als dat niet nodig is."),
        q("web-4", "Werken jullie met Next.js?", "Ja. Next.js is ideaal voor snelle, SEO-klare marketing sites en dashboards."),
        q("web-5", "Doen jullie ook PHP-applicaties?", "Ja. We bouwen portals en API’s, moderniseren legacy en harden performance en security."),
        q("web-6", "Hoe zorgen jullie voor mobiele websites?", "We ontwerpen mobile-first, bouwen responsive layouts en testen op gangbare devices en browsers, zodat de site overal goed werkt."),
        q("web-7", "Is toegankelijkheid (a11y) inbegrepen?", "We bouwen met toegankelijke basispraktijken. Strengere WCAG-trajecten kunnen we als extra scope opnemen."),
        q("web-8", "Kunnen jullie CMS-opties bieden zonder WordPress?", "Ja. Dat kan een headless CMS, custom admin of een statische setup zijn — afhankelijk van jullie team en wensen."),
        q("web-9", "Hoe lang duurt een webdesigntraject?", "Landingspagina’s duren meestal enkele weken; grotere sites of apps lopen in sprints over meerdere weken. De planning volgt na de intake."),
        q("web-10", "Regelen jullie ook copy en SEO bij launch?", "Ja, in combinatie met content- en SEO-diensten, zodat de site meteen vindbaar en conversiegericht live gaat."),
        q("web-11", "Wat met performance na launch?", "We optimaliseren Core Web Vitals, caching of CDN en monitoring. Nazorg loopt daarna via onderhoudspakketten."),
        q("web-12", "Kunnen jullie API’s koppelen (CRM, betalingen, AI)?", "Ja. We bouwen integraties met nette foutafhandeling, logging en documentatie."),
        q("web-13", "Hoe leveren jullie code op?", "Waar mogelijk leveren we via repository en deploy pipeline, met environments (staging en production) en een duidelijke handover."),
        q("web-14", "Helpen jullie met conversie-optimalisatie op de site?", "Ja. We doen A/B-tests, UX-verbeteringen, formulieren, CTA’s en page speed, zodat meer bezoekers converteren."),
      ],
    },
    {
      id: "webhosting",
      title: "Webhosting en domeinen",
      items: [
        q("host-1", "Welke hosting bieden jullie?", "We bieden shared hosting, WordPress hosting en VPS — in Basic, Plus en Business niveaus — plus domeinen."),
        q("host-2", "Wat is het verschil tussen shared, WordPress en VPS?", "Shared is voordelig voor kleinere sites. WordPress hosting is geoptimaliseerd voor WP. VPS geeft meer resources en controle voor zwaardere loads."),
        q("host-3", "Helpen jullie met domeinregistratie?", "Ja. We adviseren, registreren of verhuizen het domein en koppelen DNS correct."),
        q("host-4", "Zit SSL bij hosting?", "Ja. SSL is standaard in onze relevante hostingplannen."),
        q("host-5", "Kunnen jullie mijn site migreren naar jullie hosting?", "Ja. We doen backup, migratie, DNS-cutover, SSL en smoke tests, met minimale downtime."),
        q("host-6", "Hoe werken backups op hosting?", "Dat hangt van het plan af: eenvoudige of geautomatiseerde backups. Extra off-site retentie is mogelijk."),
        q("host-7", "Wat als ik meer traffic krijg?", "Dan schalen we naar Plus, Business of VPS en optimaliseren we caching en CDN, zodat de site de groei aankan."),
        q("host-8", "Bieden jullie e-mail bij domeinen?", "Dat hangt van het pakket en de setup af. We adviseren betrouwbare mailoplossingen en zetten DNS goed (SPF, DKIM en DMARC)."),
        q("host-9", "Hoe veilig is jullie hosting?", "We werken met firewall, SSL, updates, monitoring en hardening. Extra security-diensten kunnen daar nog lagen bovenop zetten."),
        q("host-10", "Kan ik later van shared naar VPS?", "Ja. We plannen de migratie samen, inclusief tests en rollback, zodat de overstap gecontroleerd verloopt."),
        q("host-11", "Ondersteunen jullie CDN?", "Ja, waar relevant — vaak zit er een gratis CDN in WP-hostingplannen — voor snellere globale delivery."),
        q("host-12", "Wat is jullie uptime-aanpak?", "We monitoren, reageren snel bij incidenten en communiceren duidelijk bij onderhoudsvensters, zodat jullie weten wat er speelt."),
        q("host-13", "Helpen jullie DNS-problemen oplossen?", "Ja. We lossen records, propagatie, mail-auth en domeinkoppelingen op tot DNS weer klopt."),
        q("host-14", "Hoe kies ik het juiste hostingplan?", "Op basis van traffic, stack (WordPress of maatwerk), resources en groei. We adviseren eerlijk — we verkopen niet over."),
        q("host-15", "Waar zie ik hostingprijzen?", "Op de hostingdienstpagina’s onder Diensten → Webhosting en domeinen, met maand- of jaaropties waar van toepassing."),
      ],
    },
  ],
};

const en: FaqContent = {
  title: "Frequently asked questions",
  subtitle:
    "In-depth questions and answers — from AI, AEO, GEO and SEO to design, domains, hosting, marketing, social media, support and more.",
  ctaTitle: "Still need help?",
  ctaText:
    "Can't find your question? Contact us — we'll get back to you as soon as possible.",
  ctaButton: "Contact us",
  categories: [
    {
      id: "general",
      title: "General",
      items: [
        q("gen-1", "What does TripleZero iT do exactly?", "TripleZero iT combines webdesign, WordPress support, digital marketing, search visibility (AEO, GEO/local and SEO), design and hosting. We help brands get found faster, build better websites and grow in a measurable way."),
        q("gen-2", "How do I get started with TripleZero iT?", "Contact us or book an appointment. We run a short intake, review goals and stack, then prepare a concrete proposal with planning and KPIs."),
        q("gen-3", "Which types of businesses do you work with?", "We work with SMBs, scale-ups, ecommerce, agencies and international brands. That can be alongside an existing team, or as a full-service partner."),
        q("gen-4", "Do you only work in the Netherlands?", "No. We serve clients in the Benelux and internationally, with Dutch-language and English-language engagements."),
        q("gen-5", "What does a typical engagement look like?", "A typical engagement runs like this: intake → audit or scan → plan → sprint execution → measurement → optimization. You get clear milestones and reporting, so it is always clear where we stand."),
        q("gen-6", "Can I combine multiple services?", "Yes. Many clients combine webdesign + SEO + ads, or WordPress maintenance + hosting + security. We tailor the mix to your goals and budget."),
        q("gen-7", "How soon can you start?", "It depends on our capacity, but after approval we often start within a few business days. Urgent work — such as bugs, malware or downtime — is prioritized so we can pick it up as quickly as possible."),
        q("gen-8", "Do you work remote or on-site?", "We work primarily remote, with clear communication via email, chat and calls. On-site is available on request when the project needs it."),
        q("gen-9", "How does the team communicate progress?", "We keep you updated through regular updates, tickets or a dashboard where relevant, plus sprint or monthly reports with actions and results."),
        q("gen-10", "What do you need from us to start?", "To start, we need access to the website and hosting (if required), your goals, brand guidelines, analytics accounts and any existing tools. If something is missing, we help get it in place first."),
        q("gen-11", "Are your services a fit for startups?", "Yes. We scale from lean landing pages and AI scans to full growth setups, so the approach grows with you."),
        q("gen-12", "Who owns the work and accounts?", "Your domain, content, code repositories and ad accounts stay yours. At handover we deliver the files and documentation so everything remains under your control."),
        q("gen-13", "Can you take over or collaborate with existing vendors?", "Yes. We work smoothly alongside developers, marketers or agencies, or we take over maintenance and optimization without unnecessarily disrupting existing work."),
      ],
    },
    {
      id: "ai",
      title: "AI",
      items: [
        q("ai-1", "What is an AI scan at TripleZero iT?", "An AI-readiness scan assesses how well your site can be found by classic search engines, AI answers and local or geographic search results (AEO, GEO, SEO and the technical foundations)."),
        q("ai-2", "What does the AI scan measure exactly?", "The scan measures AEO signals, GEO/local visibility, SEO fundamentals, content structure, performance indicators and AI readiness. You receive scores and concrete improvement points."),
        q("ai-3", "How often should I run an AI scan?", "At minimum after major site changes or campaigns. For active brands we recommend periodic scans, for example each quarter, so you stay visible in search and AI results."),
        q("ai-4", "Does AI only help with content?", "No. AI also affects technical discoverability, structured data, internal linking, FAQ blocks and how brand information is summarized in AI answers."),
        q("ai-5", "Can you integrate AI into our workflow?", "Yes. We can use AI for content assistance, automation, chatbot or ticket flows, data connections and custom APIs around AI tools."),
        q("ai-6", "Does AI replace your strategic work?", "No. AI speeds up analysis and production, but strategy, brand voice and conversion decisions stay human and measurable."),
        q("ai-7", "Is AI content safe for SEO?", "Only with human review, unique insights and E-E-A-T. We avoid thin, generic text that harms rankings."),
        q("ai-8", "What is AI readiness for my brand?", "It is the degree to which your site, content and data are set up so AI systems can correctly cite, recommend and explain your brand."),
        q("ai-9", "Can you use AI agents in the dashboard?", "Yes. In the client portal you see AI agents for SEO, content, social and ads — including status and tasks."),
        q("ai-10", "Do you work with ChatGPT, Claude or other tools?", "We choose tools per use case. Governance matters: sources, fact-checking, brand guidelines and privacy, so AI use stays reliable."),
        q("ai-11", "Does AI help with support tickets?", "Yes, for triage and faster replies. Complex or sensitive cases are always escalated to a human teammate."),
        q("ai-12", "What does an AI engagement cost?", "It ranges from a free or entry-level AI scan to monthly AI and marketing retainers. After intake you receive a clear proposal."),
        q("ai-13", "How do I measure ROI of AI initiatives?", "Through KPIs such as traffic, leads, time saved, content output, ticket resolution and conversion. We define those upfront in the plan so results stay visible."),
      ],
    },
    {
      id: "aeo-geo-seo",
      title: "AEO, GEO and SEO",
      items: [
        q("seo-1", "What is the difference between AEO, GEO and SEO?", "AEO (Answer Engine Optimization) focuses on AI answers. GEO (Geographic Search Engine Optimization) strengthens local and regional visibility in Maps, local packs and location-based search. SEO optimizes for classic search engines."),
        q("seo-2", "Why do AEO/GEO matter now?", "More searchers get answers via AI and also search locally (“near me”). Without AEO you miss AI citations; without GEO you miss local leads — even when classic SEO is solid."),
        q("seo-3", "How do you start an SEO engagement?", "We start with a technical audit, keyword and intent research, a content-gap analysis and a priority roadmap linked to your business KPIs."),
        q("seo-4", "How long until SEO results become visible?", "Technical wins can show quickly. Organic growth usually builds over weeks to months, depending on competition and how consistently we execute."),
        q("seo-5", "Do you also do local SEO?", "Yes. We work on Google Business Profile, local landing pages, NAP consistency, reviews and local content clusters so you are found better in your region."),
        q("seo-6", "What is technical SEO for you?", "Technical SEO covers crawlability, indexation, Core Web Vitals, structured data, sitemap and robots, canonicals, internal linking and error cleanup — everything search engines need to understand the site well."),
        q("seo-7", "Do you help with content for SEO?", "Yes. We create briefs, outlines, blogs, landing pages and FAQs that match search intent and are structured in an AI-friendly way."),
        q("seo-8", "What is E-E-A-T and why does it matter?", "E-E-A-T stands for Experience, Expertise, Authoritativeness and Trust. Strong E-E-A-T helps rankings and your brand’s credibility in AI summaries."),
        q("seo-9", "Do you do link building?", "Yes, ethically and relevantly: digital PR, partnerships and content assets. We do not use spammy link schemes."),
        q("seo-10", "Can you repair existing SEO damage?", "Yes. We repair damage after updates, toxic links, indexation problems or content cannibalization, then set a clean growth path."),
        q("seo-11", "How do you report SEO progress?", "Monthly or per sprint we report rankings, traffic, conversions, technical issues and next actions, so it is clear what we did and what comes next."),
        q("seo-12", "Does SEO work for ecommerce?", "Absolutely. We optimize product and category SEO, faceted navigation, reviews, structured data and content hubs around purchase intent."),
        q("seo-13", "Is SEO a one-off project or ongoing?", "The best results come from ongoing optimization. One-off audits help, but competitors do not stand still — that is why we keep measuring and adjusting."),
        q("seo-14", "Do you help with international SEO?", "Yes. We handle hreflang, market research per country or language, content localization and technical multi-locale setups."),
      ],
    },
    {
      id: "advertising",
      title: "Advertising",
      items: [
        q("ads-1", "Which advertising channels do you support?", "We support Google Ads, Meta (Facebook/Instagram), LinkedIn, and where relevant YouTube or retargeting — aligned to funnel and budget."),
        q("ads-2", "How do you determine the right advertising budget?", "We set the budget based on goals (leads or sales), CAC targets, market prices and a test phase. We start lean and scale what works."),
        q("ads-3", "What is your approach to Google Ads?", "We set a clear account structure, map search intent, add negative keywords, check landing-page fit, set up conversion tracking and optimize weekly."),
        q("ads-4", "Can you run Meta Ads for ecommerce?", "Yes. We run catalog and retargeting campaigns, test creatives and audiences, and optimize to improve ROAS."),
        q("ads-5", "How do you measure advertising success?", "We measure conversions, CPA/CAC, ROAS, lead quality and pipeline — not clicks alone. That way we optimize for results instead of volume."),
        q("ads-6", "What if tracking is wrong?", "Then we fix tagging (GTM, GA4 and pixels), consent mode where needed, and server-side options for more reliable data."),
        q("ads-7", "Do you also run B2B LinkedIn Ads?", "Yes. We use sharp targeting, lead-gen forms or landing pages and content that speaks to decision-makers."),
        q("ads-8", "How quickly will I see results from ads?", "Traffic can arrive immediately. Stable CPA or ROAS usually needs 2 to 6 weeks of learning and creative iteration."),
        q("ads-9", "Do you also create ad creatives?", "Yes. We create copy, visuals and test variants. Design and media creation can be included so campaigns do not wait on creatives."),
        q("ads-10", "Can ads and SEO reinforce each other?", "Absolutely. Search data from ads feeds SEO; strong organic pages lower CPA and raise Quality Score."),
        q("ads-11", "Do you manage existing ad accounts?", "Yes. We audit, restructure and optimize without unnecessarily starting over."),
        q("ads-12", "How do you prevent wasted ad budget?", "We prevent waste with negative keywords, audience exclusions, budget caps, geofencing, frequency control and quickly pausing underperformers."),
        q("ads-13", "Is remarketing still relevant?", "Yes, when it is privacy-compliant and paired with strong creatives and offers. It often remains the most efficient layer in the funnel."),
      ],
    },
    {
      id: "design",
      title: "Design",
      items: [
        q("des-1", "Which design services do you offer?", "We offer logos, brand identity, business cards, letterhead, flyers, posters, stickers, magazines or brochures and digital visuals."),
        q("des-2", "Which tools do you work in?", "We work in Adobe Photoshop, Illustrator and InDesign so files are print-ready and professionally interchangeable."),
        q("des-3", "Do you deliver print-ready files?", "Yes. We deliver CMYK, bleed, crop marks and the right PDF/X export where needed, plus screen variants for digital use."),
        q("des-4", "How does a logo project work?", "A logo project runs from briefing to concepts, then feedback rounds, and ends with final vector files (SVG/PDF/AI) and basic guidelines."),
        q("des-5", "Can you update our existing brand?", "Yes. We refresh logo, color, typography and applications without breaking recognition."),
        q("des-6", "Do you also make social templates?", "Yes. We create consistent templates for posts, stories and ads so your team can publish quickly and recognizably."),
        q("des-7", "What is the difference between digital and print design?", "Print needs color space, resolution and trim margins; digital needs sharpness on screens and fast load times. We deliver both correctly, tailored to the channel."),
        q("des-8", "Can you layout magazines or brochures?", "Yes. We create multi-page layouts in InDesign with grid, styles and prepress checks, ready for print or digital distribution."),
        q("des-9", "Do you help with printing?", "Yes. We design and can print in small or large quantities — from business cards and stickers to flyers, posters and brochures — with proofs and coordination through delivery."),
        q("des-10", "How many feedback rounds are included?", "Usually 2 to 3 structured rounds are included. Extra rounds are possible by agreement."),
        q("des-11", "Do we get source files?", "Yes, within the agreed delivery. That can be AI, PSD or INDD, or an export pack — depending on what we agreed."),
        q("des-12", "Can design and webdesign run together?", "Yes. We align brand design and UI systems so print and website form one whole."),
        q("des-13", "Where can I learn more about Digital Design?", "More information is on /digital-design and via the Digital Design services in the menu."),
      ],
    },
    {
      id: "marketing",
      title: "Marketing",
      items: [
        q("mkt-1", "Which marketing services do you offer?", "We offer AEO/GEO/SEO, content, social, ads, ecommerce growth, product listing, community management and data entry."),
        q("mkt-2", "How do you build a marketing strategy?", "We build a strategy around goals, audience, positioning, channel mix, content pipeline and KPIs — practical and executable, not only on paper."),
        q("mkt-3", "What is full-funnel marketing for you?", "Full-funnel runs from awareness (content and ads) through consideration (cases and SEO) to conversion (landing pages and CRM) and then retention, so every stage has a clear role."),
        q("mkt-4", "Do you help with positioning?", "Yes. Clear positioning prevents fragmented campaigns and weak conversion."),
        q("mkt-5", "Can you deliver content writing?", "Yes. We write blogs, website copy, newsletters, landing pages and sales copy — SEO- and conversion-focused."),
        q("mkt-6", "Do you do ecommerce marketing?", "Yes. We work on product feeds, listing quality, CRO, ads and SEO for categories and products."),
        q("mkt-7", "What is CRO?", "CRO is Conversion Rate Optimization: improving pages, funnels and UX so more visitors convert."),
        q("mkt-8", "How do you report marketing results?", "We report through dashboards or reports with traffic, leads, sales, CPA/ROAS and learnings per channel, including what we do next."),
        q("mkt-9", "Do you work with our internal marketing team?", "Yes. We can execute, spar or take over a specialist part, for example SEO only or ads only."),
        q("mkt-10", "How quickly do you launch campaigns?", "After tracking and setup, campaigns often go live within 1 to 2 weeks. Content work runs in parallel so creatives and pages are ready on time."),
        q("mkt-11", "Do you help with email marketing?", "Yes. We create flows, newsletters and copy. Integration with CRM or ecommerce is possible."),
        q("mkt-12", "Is marketing a monthly contract?", "Retainers are common for ongoing growth. Projects such as an audit, redesign or launch can be one-off."),
        q("mkt-13", "How do you prevent “busy marketing” without results?", "Every activity is tied to KPIs. Underperforming tactics are stopped or improved with data, so budget goes to what works."),
      ],
    },
    {
      id: "social-media",
      title: "Social Media",
      items: [
        q("soc-1", "Which social channels do you manage?", "We mainly manage LinkedIn, Instagram and Facebook, and where relevant X or TikTok — based on audience, not hype."),
        q("soc-2", "What is included in social media management?", "Social media management covers strategy, content calendar, creation and scheduling, community replies, reporting and ongoing optimization."),
        q("soc-3", "Do you also create the visuals and videos?", "Yes, via media creation: stills, carousels, short-form video and templates."),
        q("soc-4", "How often do you post?", "That depends on channel and goals. Typically we post 3 to 5 times per week per core channel, with quality over volume."),
        q("soc-5", "Do you help with community management?", "Yes. We handle moderation, replies, DMs and reputation care according to the agreed tone of voice."),
        q("soc-6", "Can social and ads be combined?", "Yes. Organic content feeds ad creatives; ads scale what performs organically."),
        q("soc-7", "How do you measure social success?", "We measure reach, engagement, click-outs, leads and assisted conversions — not likes alone. That shows what truly contributes to growth."),
        q("soc-8", "Do you work with influencers?", "On request: selection, briefing and tracking. We focus on fit and measurable outcomes, not reach alone."),
        q("soc-9", "Can you support crisis communication?", "Yes. We use fast response protocols and align with your team so replies stay consistent and under control."),
        q("soc-10", "Do you help with LinkedIn for B2B thought leadership?", "Yes. We create personal and company content, carousels, cases and employee advocacy so expertise becomes visible."),
        q("soc-11", "Do you deliver a content calendar?", "Yes. We deliver a monthly or quarterly plan with themes, formats and deadlines."),
        q("soc-12", "What if we already have a social manager?", "Then we can specialize in creatives, ads or strategy, or support peak periods without replacing the existing team."),
        q("soc-13", "How quickly will we see growth on social?", "Consistency matters. Significant growth usually takes weeks to months; with ads support it often goes faster."),
      ],
    },
    {
      id: "support",
      title: "Support",
      items: [
        q("sup-1", "What support do you offer?", "We offer WordPress support, custom website support, tickets and live chat, maintenance, security, performance and incident response."),
        q("sup-2", "How do I reach support?", "Via contact, an appointment, tickets in the dashboard or live chat on the site. Urgent cases are marked as priority."),
        q("sup-3", "What is your response time?", "We aim for a fast first response, often within one business day. For critical downtime we respond faster. Exact SLAs are in the support packages."),
        q("sup-4", "Do you offer 24/7 monitoring?", "Yes, in relevant support and hosting packages: monitoring, backups and alerts so problems become visible earlier."),
        q("sup-5", "Can you remove malware?", "Yes — on WordPress as well as custom stacks — including hardening and aftercare so the site comes back clean and better protected."),
        q("sup-6", "Do you handle WordPress updates for us?", "Yes, via “Maintenance and updates”: core, plugins and themes, with backup and checks before and after we update."),
        q("sup-7", "Do you help with hosting problems?", "Yes. We diagnose, migrate or optimize hosting, VPS and domains until the site runs stably again."),
        q("sup-8", "What if my site is down?", "Report it as urgent. We restore where possible via backups, server checks and a hotfix, and keep you updated on status along the way."),
        q("sup-9", "Is there a client portal?", "Yes. Logged-in clients see dashboard, tickets, projects and where relevant CRM or invoices."),
        q("sup-10", "Can multiple teammates open tickets?", "Yes, depending on account roles (client, manager or admin)."),
        q("sup-11", "What is included in Basic/Standard/Premium support?", "Higher packages cover more sites, faster follow-up and broader coverage (updates, malware, speed, SEO). Details are on the support pages."),
        q("sup-12", "Do you also help with non-technical questions?", "Yes, about services, billing and account. How deep we go technically depends on your package."),
        q("sup-13", "Can I upgrade support later?", "Yes. You can scale up when traffic, risk or team needs grow."),
      ],
    },
    {
      id: "webdesign",
      title: "Webdesign",
      items: [
        q("web-1", "Do you only build WordPress sites?", "No. Besides WordPress we do custom webdesign in HTML/CSS/JS, PHP and Next.js — separate from the WordPress services."),
        q("web-2", "What does Website Support include?", "Website Support covers design, development, maintenance, security, performance, backups or migration and API integrations for custom stacks."),
        q("web-3", "Can you redesign an existing site?", "Yes. We do a UX/UI refresh, conversion improvements and technical modernization, without throwing everything away if that is not needed."),
        q("web-4", "Do you work with Next.js?", "Yes. Next.js is ideal for fast, SEO-ready marketing sites and dashboards."),
        q("web-5", "Do you also build PHP applications?", "Yes. We build portals and APIs, modernize legacy and harden performance and security."),
        q("web-6", "How do you ensure mobile websites?", "We design mobile-first, build responsive layouts and test on common devices and browsers so the site works everywhere."),
        q("web-7", "Is accessibility (a11y) included?", "We build with accessible baseline practices. Stricter WCAG programs can be included as extra scope."),
        q("web-8", "Can you offer CMS options without WordPress?", "Yes. That can be a headless CMS, custom admin or a static setup — depending on your team and needs."),
        q("web-9", "How long does a webdesign project take?", "Landing pages usually take a few weeks; larger sites or apps run in sprints over multiple weeks. Planning follows after intake."),
        q("web-10", "Do you also handle copy and SEO at launch?", "Yes, combined with content and SEO services so the site goes live searchable and conversion-focused right away."),
        q("web-11", "What about performance after launch?", "We optimize Core Web Vitals, caching or CDN and monitoring. Aftercare then continues via maintenance packages."),
        q("web-12", "Can you connect APIs (CRM, payments, AI)?", "Yes. We build integrations with clean error handling, logging and documentation."),
        q("web-13", "How do you deliver code?", "Where possible we deliver via repository and deploy pipeline, with environments (staging and production) and a clear handover."),
        q("web-14", "Do you help with on-site conversion optimization?", "Yes. We run A/B tests, UX improvements, forms, CTAs and page speed so more visitors convert."),
      ],
    },
    {
      id: "webhosting",
      title: "Webhosting and domains",
      items: [
        q("host-1", "Which hosting do you offer?", "We offer shared hosting, WordPress hosting and VPS — in Basic, Plus and Business tiers — plus domains."),
        q("host-2", "What is the difference between shared, WordPress and VPS?", "Shared is cost-effective for smaller sites. WordPress hosting is optimized for WP. VPS gives more resources and control for heavier loads."),
        q("host-3", "Do you help with domain registration?", "Yes. We advise, register or transfer the domain and connect DNS correctly."),
        q("host-4", "Is SSL included with hosting?", "Yes. SSL is standard in our relevant hosting plans."),
        q("host-5", "Can you migrate my site to your hosting?", "Yes. We handle backup, migration, DNS cutover, SSL and smoke tests, with minimal downtime."),
        q("host-6", "How do backups work on hosting?", "That depends on the plan: simple or automated backups. Extra off-site retention is available."),
        q("host-7", "What if I get more traffic?", "Then we scale to Plus, Business or VPS and optimize caching and CDN so the site can handle the growth."),
        q("host-8", "Do you offer email with domains?", "That depends on the package and setup. We advise reliable mail solutions and set DNS correctly (SPF, DKIM and DMARC)."),
        q("host-9", "How secure is your hosting?", "We use firewall, SSL, updates, monitoring and hardening. Extra security services can add more layers on top."),
        q("host-10", "Can I move from shared to VPS later?", "Yes. We plan the migration together, including tests and rollback, so the switch stays controlled."),
        q("host-11", "Do you support CDN?", "Yes, where relevant — often a free CDN is included in WP hosting plans — for faster global delivery."),
        q("host-12", "What is your uptime approach?", "We monitor, respond quickly to incidents and communicate clearly around maintenance windows so you know what is happening."),
        q("host-13", "Do you help solve DNS problems?", "Yes. We fix records, propagation, mail auth and domain connections until DNS is correct again."),
        q("host-14", "How do I choose the right hosting plan?", "Based on traffic, stack (WordPress or custom), resources and growth. We advise honestly — we do not oversell."),
        q("host-15", "Where can I see hosting prices?", "On the hosting service pages under Services → Webhosting and domains, with monthly or yearly options where applicable."),
      ],
    },
  ],
};

export function getFaqContent(locale: string): FaqContent {
  const pack = loadFaqPack(locale);
  if (pack) {
    return {
      title: pack.title,
      subtitle: pack.subtitle,
      ctaTitle: pack.ctaTitle,
      ctaText: pack.ctaText,
      ctaButton: pack.ctaButton,
      categories: pack.categories.map((category) => ({
        id: category.id,
        title: category.title,
        items: category.items.map((item) => ({
          id: item.id,
          question: item.question,
          answer: item.answer,
        })),
      })),
    };
  }
  // Legacy inline fallback if JSON packs are missing
  return locale === "nl" ? nl : en;
}
